### ISSUE TITLE
'zfs set sharesmb=off dataset' does not issue 'net usershare delete sharename' to Samba

### ISSUE THREAD

**Issue by AngryChris** [zfsonlinux/zfs#1996]
Sharing out a dataset over Samba works fine by setting the zfs property 'sharesmb' to on.  This share can be viewed using either smbclient or net info.  However, unsharing the dataset with 'zfs set sharesmb=off dataset' does not tell Samba to stop sharing it.

The man page for zfs indicates that setting this property to off should automatically unshare the dataset.  This doesn't happen and the dataset remains shared despite the sharesmb property being set to off.  In order to remove the share, one has to run 'net usershare delete sharename' which is "going over the head" of zfs itself.

I do understand that setting and unsetting this property is essentially a shortcut to sharing or unsharing something via net, but this portion of the shortcut isn't working.

I am using zfs 0.6.2 on Ubuntu Server 12.04 LTS using kmod packages:

```
[0] cbell@circe:/home/cbell 617-> dpkg -l | awk '{print $2" "$3}' | grep -e zfs -e spl
kmod-spl-3.2.0-57-generic 0.6.2-1
kmod-zfs-3.2.0-57-generic 0.6.2-1
mountall 2.36.4-zfs2
zfs 0.6.2-1
[0] cbell@circe:/home/cbell 618->
```

mountall is from the Ubuntu PPA, the other packages are built using the generic deb instructions on a git checkout of 0.6.2.  I've not been able to find if this issue is documented anywhere else so this could be an issue with my setup.

```
[0] cbell@circe:/home/cbell 619-> uname -a
Linux circe 3.2.0-57-generic #87-Ubuntu SMP Tue Nov 12 21:35:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
[0] cbell@circe:/home/cbell 620->
```

**Comment by theostauffer** [comment]
@AngryChris Thanks for posting your original comment and observation. I was going a little bit nuts with this.

**Comment by loli10K** [comment]
While working to enable `zfs_share`/`zfs_unshare` tests in the ZTS i found a problem in `smb_is_share_active()` that would leave SMB shares exported when trying to unshare them, so i tried to address it in https://github.com/zfsonlinux/zfs/pull/5367: maybe that also fixed this issue?

**Comment by loli10K** [comment]
Supposedly fixed by https://github.com/zfsonlinux/zfs/commit/2f71caf2d926249920d1b9162550c56715cc6461, closing.

**Comment by llamafilm** [comment]
I think this is not fixed.  Running ZFS 0.8.1-1 on CentOS 7.6.

```
$ net usershare list

$ zfs set sharesmb=on tank/data

$ net usershare list
tank_data

$ zfs set sharesmb=off tank/data

$ net usershare list
tank_data
```

**Comment by gitercn** [comment]
> I think this is not fixed. Running ZFS 0.8.1-1 on CentOS 7.6.
> 
> ```
> $ net usershare list
> 
> $ zfs set sharesmb=on tank/data
> 
> $ net usershare list
> tank_data
> 
> $ zfs set sharesmb=off tank/data
> 
> $ net usershare list
> tank_data
> ```

I think it's not fixed as well, using ZFS 0.8.4 on Proxmox VE. BTW, what's the advantage/disvantage by using `zfs set sharesmb=on pool` verses using `\etc\samba\smb.conf` to set the samba share?
