### ISSUE TITLE
zpool import freezes

### ISSUE THREAD

**Issue by Grumbel** [zfsonlinux/zfs#2947]
Running Ubuntu 14.10 with Linux 3.16.0-25-lowlatency and zfsonlinux 0.6.3-13~utopic from the PPA. 

I have here a USB HDD that I use for backup. When I try to import the pool on that HDD via:

```
$ zpool import backup
```

It just hangs, other zfs commands will hang as well. Rest of Linux still seems to be running fine and other non-zfs filesystems on the same HDD also continue to work.

On `dmesg` I see this as soon as I try to run the `zpool import`:

```
[  186.614848] Call Trace:
[  186.614860]  [<ffffffff8177efcd>] dump_stack+0x4d/0x6f
[  186.614899]  [<ffffffffc04fe4e7>] spl_debug_dumpstack+0x27/0x40 [spl]
[  186.614907]  [<ffffffffc04ff840>] spl_debug_bug+0x80/0xe0 [spl]
[  186.614986]  [<ffffffffc05e45c0>] space_map_add+0x1c0/0x390 [zfs]
[  186.615023]  [<ffffffffc05e4400>] ? space_map_find+0x160/0x160 [zfs]
[  186.615073]  [<ffffffffc05e4d08>] space_map_load+0x1a8/0x3b0 [zfs]
[  186.615107]  [<ffffffffc05ca54e>] metaslab_activate+0xde/0x160 [zfs]
[  186.615139]  [<ffffffffc05cbe95>] metaslab_alloc+0x665/0xbd0 [zfs]
[  186.615154]  [<ffffffff810aaaa8>] ? __enqueue_entity+0x78/0x80
[  186.615163]  [<ffffffff810b1a80>] ? enqueue_entity+0x400/0xca0
[  186.615176]  [<ffffffff8101ebae>] ? native_sched_clock+0x2e/0xc0
[  186.615222]  [<ffffffffc062dac8>] zio_dva_allocate+0x88/0x430 [zfs]
[  186.615263]  [<ffffffffc062a102>] ? zio_push_transform+0x42/0x90 [zfs]
[  186.615320]  [<ffffffffc062b7f5>] zio_execute+0xb5/0x150 [zfs]
[  186.615334]  [<ffffffffc0509157>] taskq_thread+0x247/0x4c0 [spl]
[  186.615342]  [<ffffffff8109e42f>] ? finish_task_switch+0x4f/0x150
[  186.615346]  [<ffffffff810a6150>] ? wake_up_state+0x20/0x20
[  186.615355]  [<ffffffffc0508f10>] ? taskq_cancel_id+0x1f0/0x1f0 [spl]
[  186.615361]  [<ffffffff8109569b>] kthread+0xdb/0x100
[  186.615364]  [<ffffffff810955c0>] ? kthread_create_on_node+0x1c0/0x1c0
[  186.615369]  [<ffffffff8178693c>] ret_from_fork+0x7c/0xb0
[  186.615373]  [<ffffffff810955c0>] ? kthread_create_on_node+0x1c0/0x1c0
```

**Comment by kpande** [comment]
@behlendorf do you think this was resolved with the changes referenced above?

**Comment by behlendorf** [comment]
@kpande we've seen a few similar reports of this kind of issue over the last year so it's hard to say for certain.  A rare variant of this may still exist in 0.6.5.x.  The master code is a different story due the extensive changes made to metaslab handling.  However, due to the age of this bug I think we should close it.  We'll want to open a new bug if this is observed again with more current code.
