### ISSUE TITLE
BUG: Bad page state in process

### ISSUE THREAD

**Issue by mmessaoudi22** [zfsonlinux/zfs#3309]
Dear All,

I have a server running rdiff-backup on several zfs pools. After upgrading from 0.6.3 to 0.6.4, we noticed several messages "BUG: Bad page state in process" in the log.
We were running kernel 3.14.22 (vanilla) and upgraded to 3.14.38 but same messages again.
The server was running with no issues with release 0.6.3.

Do you have any idea ?
Your help would be much appreciated.

Here is an extract from the log file:
[  829.731633] CPU: 0 PID: 0 Comm: swapper/0 Tainted: P    B      O 3.14.38-scst_301-20150415 #2
[  829.731634] Hardware name: HP ProLiant DL380p Gen8, BIOS P70 02/10/2014
[  829.731635]  ffffffff817c6e73 ffff881fbfa03948 ffffffff816614ba ffffea00fbcdafc0
[  829.731637]  ffff881fbfa03970 ffffffff8110ba9b ffffea00fbcdafc0 0000000000000000
[  829.731639]  ffffea00fbcdb000 ffff881fbfa039b8 ffffffff8110bc0c ff0001ffffffffff
[  829.731641] Call Trace:
[  829.731642]  <IRQ>  [<ffffffff816614ba>] dump_stack+0x45/0x56
[  829.731650]  [<ffffffff8110ba9b>] bad_page+0xab/0x100
[  829.731652]  [<ffffffff8110bc0c>] free_pages_prepare+0x11c/0x1a0
[  829.731654]  [<ffffffff8110bd8c>] __free_pages_ok+0x1c/0x400
[  829.731657]  [<ffffffff8115729e>] ? __slab_free+0x9e/0x320
[  829.731659]  [<ffffffff8110c186>] free_compound_page+0x16/0x20
[  829.731661]  [<ffffffff81111b8a>] __put_compound_page+0x1a/0x20
[  829.731663]  [<ffffffff81112220>] put_compound_page+0x80/0x1b0
[  829.731665]  [<ffffffff81112375>] put_page+0x25/0x30
[  829.731669]  [<ffffffff814d96fb>] skb_release_data+0x9b/0x110
[  829.731671]  [<ffffffff814d978f>] skb_release_all+0x1f/0x30
[  829.731673]  [<ffffffff814d97ad>] __kfree_skb+0xd/0x20
[  829.731676]  [<ffffffff81538c22>] tcp_ack+0x612/0x1270
[  829.731678]  [<ffffffff81539cdf>] tcp_rcv_established+0xdf/0x650
[  829.731680]  [<ffffffff81543b75>] tcp_v4_do_rcv+0x195/0x4b0
[  829.731683]  [<ffffffff81269431>] ? security_sock_rcv_skb+0x11/0x20
[  829.731685]  [<ffffffff81545fbb>] tcp_v4_rcv+0x79b/0x7b0
[  829.731687]  [<ffffffff814d7c35>] ? skb_copy_bits+0x125/0x2a0
[  829.731690]  [<ffffffff81520cb2>] ip_local_deliver_finish+0xa2/0x210
[  829.731692]  [<ffffffff81520fe0>] ip_local_deliver+0x80/0x90
[  829.731693]  [<ffffffff81520950>] ip_rcv_finish+0x80/0x340
[  829.731695]  [<ffffffff815212a3>] ip_rcv+0x2b3/0x380
[  829.731697]  [<ffffffff814e8f97>] __netif_receive_skb_core+0x437/0x8e0
[  829.731701]  [<ffffffff8100b9b9>] ? read_tsc+0x9/0x20
[  829.731703]  [<ffffffff814e9456>] __netif_receive_skb+0x16/0x70
[  829.731705]  [<ffffffff814e94d8>] netif_receive_skb_internal+0x28/0x90
[  829.731707]  [<ffffffff814e9ea8>] napi_gro_frags+0x88/0x130
[  829.731712]  [<ffffffffa04810a6>] be_poll+0xae6/0xda0 [be2net]
[  829.731715]  [<ffffffff813c9b32>] ? scsi_io_completion+0x2c2/0x610
[  829.731717]  [<ffffffff814e989a>] net_rx_action+0x13a/0x250
[  829.731721]  [<ffffffff81054377>] __do_softirq+0xb7/0x2a0
[  829.731723]  [<ffffffff810546c5>] irq_exit+0x95/0xa0
[  829.731725]  [<ffffffff81004ea1>] do_IRQ+0x51/0xe0
[  829.731727]  [<ffffffff816693ad>] common_interrupt+0x6d/0x6d
[  829.731728]  <EOI>  [<ffffffff8103e296>] ? native_safe_halt+0x6/0x10
[  829.731735]  [<ffffffff8100ccdf>] default_idle+0x1f/0xc0
[  829.731736]  [<ffffffff8100d546>] arch_cpu_idle+0x26/0x30
[  829.731739]  [<ffffffff810995cd>] cpu_startup_entry+0xbd/0x280
[  829.731741]  [<ffffffff8165c372>] rest_init+0x72/0x80
[  829.731744]  [<ffffffff81945dcb>] start_kernel+0x3d2/0x3df
[  829.731746]  [<ffffffff81945120>] ? early_idt_handlers+0x120/0x120
[  829.731748]  [<ffffffff819454b3>] x86_64_start_reservations+0x2a/0x2c
[  829.731750]  [<ffffffff819455f8>] x86_64_start_kernel+0x143/0x152
[  829.739917] BUG: Bad page state in process swapper/0  pfn:3ef28b7
[  829.739992] page:ffffea00fbca2dc0 count:0 mapcount:-1 mapping:          (null) index:0x0
[  829.740129] page flags: 0x6fffe0000008000(tail)
[  829.740205] page dumped because: nonzero mapcount
[  829.740271] Modules linked in: fuse dm_snapshot dm_bufio mptctl mptbase sg zfs(PO) zcommon(PO) znvpair(PO) spl(O) zavl(PO) zunicode(PO) drbd(O) libcrc32c bonding dm_mod ttm drm_kms_helper sysimgblt be2iscsi(O) crct10dif_pclmul sysfillrect ghash_clmulni_intel syscopyarea iTCO_wdt crc32_pclmul crc32c_intel aesni_intel ablk_helper cryptd iscsi_boot_sysfs lrw gf128mul kvm_intel kvm glue_helper aes_x86_64 libiscsi x86_pkg_temp_thermal coretemp scsi_transport_iscsi intel_powerclamp be2net(O) hpilo iTCO_vendor_support hpwdt shpchp rtc_cmos pata_acpi ata_generic ioatdma dca ipmi_si ipmi_msghandler lpc_ich mfd_core wmi button thermal processor acpi_power_meter ata_piix uhci_hcd hpsa(O)

**Comment by behlendorf** [comment]
While nothing ZFS related appears in that stack trace there is one _possibly_ related bug in our tracker, #3075.  There's a proposed fix in #3152 which is on the short list to be reviewed and merged.  The patch is safe to cherry pick if you'd like to see if it resolved your issue.  It's a long shot though since nothing in that stack suggests ZFS has anything to do with your issue.  If ZFS isn't critical for this system you could also rule it out but making sure the modules are unloaded.

**Comment by mmessaoudi22** [comment]
Hi

Thank you for your reply.

After applying 305040e, the issue is still there.

The only difference is that now the log shows  the trace below:

 [266765.793150] Call Trace:
 [266765.793151]  <IRQ>  [<ffffffff816614ba>] dump_stack+0x45/0x56
 [266765.793155]  [<ffffffff8110ba9b>] bad_page+0xab/0x100
 [266765.793157]  [<ffffffff8110bc0c>] free_pages_prepare+0x11c/0x1a0
 [266765.793159]  [<ffffffff8110bd8c>] __free_pages_ok+0x1c/0x400
 [266765.793161]  [<ffffffff8115729e>] ? __slab_free+0x9e/0x320
 [266765.793163]  [<ffffffff8110c186>] free_compound_page+0x16/0x20
 [266765.793165]  [<ffffffff81111b8a>] __put_compound_page+0x1a/0x20
 [266765.793167]  [<ffffffff81112220>] put_compound_page+0x80/0x1b0
 [266765.793169]  [<ffffffff81112375>] put_page+0x25/0x30
 [266765.793171]  [<ffffffff814d96fb>] skb_release_data+0x9b/0x110
 [266765.793173]  [<ffffffff814d978f>] skb_release_all+0x1f/0x30
 [266765.793175]  [<ffffffff814d97ad>] __kfree_skb+0xd/0x20
 [266765.793176]  [<ffffffff81538c22>] tcp_ack+0x612/0x1270
 [266765.793178]  [<ffffffff81539cdf>] tcp_rcv_established+0xdf/0x650
 [266765.793180]  [<ffffffff8105a3c2>] ? internal_add_timer+0x12/0x40
 [266765.793182]  [<ffffffff81543b75>] tcp_v4_do_rcv+0x195/0x4b0
 [266765.793184]  [<ffffffff81269431>] ? security_sock_rcv_skb+0x11/0x20
 [266765.793186]  [<ffffffff81545fbb>] tcp_v4_rcv+0x79b/0x7b0
 [266765.793189]  [<ffffffff81520cb2>] ip_local_deliver_finish+0xa2/0x210
 [266765.793190]  [<ffffffff81520fe0>] ip_local_deliver+0x80/0x90
 [266765.793192]  [<ffffffff81520950>] ip_rcv_finish+0x80/0x340
 [266765.793194]  [<ffffffff815212a3>] ip_rcv+0x2b3/0x380
 [266765.793196]  [<ffffffff814e8f97>] __netif_receive_skb_core+0x437/0x8e0
 [266765.793198]  [<ffffffff8100b9b9>] ? read_tsc+0x9/0x20
 [266765.793200]  [<ffffffff814e9456>] __netif_receive_skb+0x16/0x70
 [266765.793202]  [<ffffffff814e94d8>] netif_receive_skb_internal+0x28/0x90
 [266765.793204]  [<ffffffff814e9ea8>] napi_gro_frags+0x88/0x130
 [266765.793207]  [<ffffffffa04810a6>] be_poll+0xae6/0xda0 [be2net]
 [266765.793209]  [<ffffffff814e989a>] net_rx_action+0x13a/0x250
 [266765.793211]  [<ffffffff81054377>] __do_softirq+0xb7/0x2a0
 [266765.793213]  [<ffffffff810546c5>] irq_exit+0x95/0xa0
 [266765.793215]  [<ffffffff81004ea1>] do_IRQ+0x51/0xe0
 [266765.793217]  [<ffffffff816693ad>] common_interrupt+0x6d/0x6d
 [266765.793217]  <EOI>  [<ffffffffa00c290d>] ? spl_kmem_free+0x2d/0x40 [spl]
 [266765.793228]  [<ffffffffa0c2d327>] ? buf_hash_insert+0x97/0x1a0 [zfs]
 [266765.793233]  [<ffffffffa0c3132f>] arc_write_done+0x9f/0x460 [zfs]
 [266765.793242]  [<ffffffffa0cd9fe9>] zio_done+0x319/0xf60 [zfs]
 [266765.793250]  [<ffffffffa0cd49ab>] ? zio_remove_child+0x12b/0x140 [zfs]
 [266765.793257]  [<ffffffffa0cda60a>] zio_done+0x93a/0xf60 [zfs]
 [266765.793264]  [<ffffffffa0cda60a>] zio_done+0x93a/0xf60 [zfs]
 [266765.793270]  [<ffffffffa0cda60a>] zio_done+0x93a/0xf60 [zfs]
 [266765.793277]  [<ffffffffa0cda60a>] zio_done+0x93a/0xf60 [zfs]
 [266765.793278]  [<ffffffff8115787e>] ? kfree+0x13e/0x150
 [266765.793285]  [<ffffffffa0cda60a>] zio_done+0x93a/0xf60 [zfs]
 [266765.793292]  [<ffffffffa0cd648c>] zio_execute+0xec/0x1b0 [zfs]
 [266765.793295]  [<ffffffffa00c61f0>] taskq_thread+0x1d0/0x380 [spl]
 [266765.793297]  [<ffffffff810817b0>] ? wake_up_state+0x10/0x10
 [266765.793299]  [<ffffffffa00c6020>] ? taskq_cancel_id+0x120/0x120 [spl]
 [266765.793301]  [<ffffffff81072566>] kthread+0xd6/0xf0
 [266765.793303]  [<ffffffff81072490>] ? kthread_create_on_node+0x180/0x180
 [266765.793305]  [<ffffffff81669b28>] ret_from_fork+0x58/0x90
 [266765.793307]  [<ffffffff81072490>] ? kthread_create_on_node+0x180/0x180

**Comment by tuxoko** [comment]
@mmessaoudi22 
```
[ 829.739992] page:ffffea00fbca2dc0 count:0 mapcount:-1 mapping: (null) index:0x0
[ 829.740129] page flags: 0x6fffe0000008000(tail)
[ 829.740205] page dumped because: nonzero mapcount
```
Is the error always with mapcount -1?
Or are there other type of errors?

**Comment by tuxoko** [comment]
@mmessaoudi22 
Also, please provide the following information:
1. Does the pool consist of iscsi disks or any other kind of over-the-network disk?
2. Which type of slab do you use: SLAB, SLUB, or SLOB?
3. spl_kmem_cache_slab_limit, spl_kmem_cache_kmem_limit

**Comment by tuxoko** [comment]
@mmessaoudi22 
I see your using scst.
Never mind my questions, I'm not likely to look into this.

**Comment by mmessaoudi22** [comment]
Hi

Just in case, I will answer the questions.
First, scst is not running on the server but drbd is.
Yes, mapcount is always -1.
The pool is using a local lv no over-the-network disk
slab used is SLUB
spl_kmem_cache_slab_limit=16384
spl_kmem_cache_kmem_limit=2048

**Comment by tuxoko** [comment]
@mmessaoudi22 
Thanks for the info, but I can't figure out how this could be caused by zfs.
If this is easily reproducible, perhaps you could try bisecting it.

**Comment by mmessaoudi22** [comment]
After reading your comments (scst), I found that there was issues caused by scst patches in some old posts.
I will do a test with an unpatched kernel to see if I get better results.

**Comment by mmessaoudi22** [comment]
Hi 

Unfortunately, I have the same error with vanilla kernel 3.14.38 and 0.6.4.1.

**Comment by tuxoko** [comment]
@mmessaoudi22 
Does it only happens when using ZFS?
From the kernel log, the error always happened in the network, but you mentioned that the pool doesn't use network disks. Is not that it's impossible, but I can't figure out how ZFS would cause this.

**Comment by mmessaoudi22** [comment]
Yes, it happens only when ZFS is used. One thing to mention is that we are having more messages when the ZFS filesystem is accessed through a samba share.

**Comment by pzwahlen** [comment]
@mmessaoudi22 
Are you also using DRBD ?

I've just experienced this problem while migrating:
- from the CentOS 7.0 kernel to the CentOS 7.1 kernel
- from the scst 3.0 SVN branch to the scst GitHub (bvannasche) 3.0 branch
- from the embedded in-kernel drbd to the latest 8.4.6 drbd (taken from ELrepo)

I upgraded 2 clusters, both using ZFS-0.6.3-1.3. Only one cluster had this issue, the one using DRBD.

Cheers

**Comment by mmessaoudi22** [comment]
Yes, we are using drbd 8.4.6. I noticed that the error is occurring while accessing the zfs from a samba share. We are using a vanilla kernel with no scst patch.
We are using ZFS 0.6.4-1.

Cheers.

**Comment by ryao** [comment]
@behlendorf The torvalds/linux@178eda29ca721842f2146378e73d43e0044c4166 commit description seems to explain this.

@tuxoko given that you wrote that patch, do you think it is possible that bug is affecting people in this issue too?

**Comment by DeHackEd** [comment]
I've seen this just today using drbd. No ZFS in the stacks except when the NIC interrupt occurs during ZFS operations. They happened frequently during a 'drbdadm verify' operation and stopped when it finished.

ZFS version 3b36f831 + ABD from the era merged in. (Full stack if you care: dehacked/zfs@edf4a7823e967b4e19). CentOS 7 kernel 3.10.0-229.14.1.el7.x86_64

**Comment by devZer0** [comment]
i see this "BUG: Bad page state" on a centos7 linux vm while zrep`ing (http://www.bolthole.com/solaris/zrep/ )  a complex zpool (containing millions of files with hundreds of snapshots) to another zpool located on a remote iscsi device.

[root@backupvm1 oops-2017-02-21-15:01:16-8298-1]# dmesg|grep -i "Bad page state"
[ 5411.262757] BUG: Bad page state in process z_wr_iss  pfn:84f35
[ 5411.320423] BUG: Bad page state in process z_wr_iss  pfn:84f36
[ 5411.393046] BUG: Bad page state in process z_wr_iss  pfn:84f37
[ 5417.148713] BUG: Bad page state in process kworker/u30:0  pfn:a85fc
[ 5417.209609] BUG: Bad page state in process kworker/u30:0  pfn:a85fd
[ 5417.273961] BUG: Bad page state in process kworker/u30:0  pfn:a85fe
[ 5417.337150] BUG: Bad page state in process kworker/u30:0  pfn:a85ff
[10447.797624] BUG: Bad page state in process z_wr_iss  pfn:810a5
[10447.856466] BUG: Bad page state in process z_wr_iss  pfn:810a6
[10447.928191] BUG: Bad page state in process z_wr_iss  pfn:810a7
[14560.927347] BUG: Bad page state in process swapper/2  pfn:b330c
[14560.964152] BUG: Bad page state in process swapper/2  pfn:b330d
[14561.021068] BUG: Bad page state in process swapper/2  pfn:b330e
[14561.078058] BUG: Bad page state in process swapper/2  pfn:b330f
[16474.198475] BUG: Bad page state in process swapper/2  pfn:7cee9
[16474.240584] BUG: Bad page state in process swapper/2  pfn:7ceea
[16474.296262] BUG: Bad page state in process swapper/2  pfn:7ceeb
[16502.914438] BUG: Bad page state in process swapper/2  pfn:23f1c
[16502.972026] BUG: Bad page state in process swapper/2  pfn:23f1d
[16503.030931] BUG: Bad page state in process swapper/2  pfn:23f1e
[16503.088058] BUG: Bad page state in process swapper/2  pfn:23f1f
[18504.115710] BUG: Bad page state in process z_wr_iss  pfn:52866
[18504.167373] BUG: Bad page state in process z_wr_iss  pfn:52867
[19480.947815] BUG: Bad page state in process z_wr_iss  pfn:7549c
[19481.014037] BUG: Bad page state in process z_wr_iss  pfn:7549d
[19481.079270] BUG: Bad page state in process z_wr_iss  pfn:7549e
[19481.143459] BUG: Bad page state in process z_wr_iss  pfn:7549f
[23689.177641] BUG: Bad page state in process z_wr_iss  pfn:279b6
[23689.230092] BUG: Bad page state in process z_wr_iss  pfn:279b7

i`m not sure if it`s centos, xenserver, zfsonlinux or iscsi related issue, but apparently it happens multiple times.

the initial zrep sync is still running, though

[root@backupvm1 oops-2017-02-21-15:01:16-8298-1]# modinfo zfs|head
filename:       /lib/modules/3.10.0-514.6.1.el7.x86_64/weak-updates/zfs.ko
version:        0.6.5.9-1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
rhelversion:    7.3
srcversion:     42C4AB70887EA26A9970936
depends:        spl,znvpair,zcommon,zunicode,zavl
vermagic:       3.10.0-514.2.2.el7.x86_64 SMP mod_unload modversions
parm:           zvol_inhibit_dev:Do not create zvol device nodes (uint)

[dmesg.txt](https://github.com/zfsonlinux/zfs/files/790942/dmesg.txt)

**Comment by devZer0** [comment]
zrep still running since yesterday - but more oops`es in different processes

[root@backupvm1 backup]# dmesg|grep BUG
[ 5411.262757] BUG: Bad page state in process z_wr_iss  pfn:84f35
[ 5411.320423] BUG: Bad page state in process z_wr_iss  pfn:84f36
[ 5411.393046] BUG: Bad page state in process z_wr_iss  pfn:84f37
[ 5417.148713] BUG: Bad page state in process kworker/u30:0  pfn:a85fc
[ 5417.209609] BUG: Bad page state in process kworker/u30:0  pfn:a85fd
[ 5417.273961] BUG: Bad page state in process kworker/u30:0  pfn:a85fe
[ 5417.337150] BUG: Bad page state in process kworker/u30:0  pfn:a85ff
[10447.797624] BUG: Bad page state in process z_wr_iss  pfn:810a5
[10447.856466] BUG: Bad page state in process z_wr_iss  pfn:810a6
[10447.928191] BUG: Bad page state in process z_wr_iss  pfn:810a7
[14560.927347] BUG: Bad page state in process swapper/2  pfn:b330c
[14560.964152] BUG: Bad page state in process swapper/2  pfn:b330d
[14561.021068] BUG: Bad page state in process swapper/2  pfn:b330e
[14561.078058] BUG: Bad page state in process swapper/2  pfn:b330f
[16474.198475] BUG: Bad page state in process swapper/2  pfn:7cee9
[16474.240584] BUG: Bad page state in process swapper/2  pfn:7ceea
[16474.296262] BUG: Bad page state in process swapper/2  pfn:7ceeb
[16502.914438] BUG: Bad page state in process swapper/2  pfn:23f1c
[16502.972026] BUG: Bad page state in process swapper/2  pfn:23f1d
[16503.030931] BUG: Bad page state in process swapper/2  pfn:23f1e
[16503.088058] BUG: Bad page state in process swapper/2  pfn:23f1f
[18504.115710] BUG: Bad page state in process z_wr_iss  pfn:52866
[18504.167373] BUG: Bad page state in process z_wr_iss  pfn:52867
[19480.947815] BUG: Bad page state in process z_wr_iss  pfn:7549c
[19481.014037] BUG: Bad page state in process z_wr_iss  pfn:7549d
[19481.079270] BUG: Bad page state in process z_wr_iss  pfn:7549e
[19481.143459] BUG: Bad page state in process z_wr_iss  pfn:7549f
[23689.177641] BUG: Bad page state in process z_wr_iss  pfn:279b6
[23689.230092] BUG: Bad page state in process z_wr_iss  pfn:279b7
[27943.447545] BUG: Bad page state in process swapper/1  pfn:c67f4
[27943.484447] BUG: Bad page state in process swapper/1  pfn:c67f5
[27943.489297] BUG: Bad page state in process swapper/1  pfn:c67f6
[27943.489297] BUG: Bad page state in process swapper/1  pfn:c67f7
[43710.166758] BUG: Bad page state in process z_wr_iss  pfn:a0b34
[43710.215434] BUG: Bad page state in process z_wr_iss  pfn:a0b35
[43710.281412] BUG: Bad page state in process z_wr_iss  pfn:a0b36
[43710.347920] BUG: Bad page state in process z_wr_iss  pfn:a0b37
[44484.576245] BUG: Bad page state in process txg_sync  pfn:03b95
[44484.652476] BUG: Bad page state in process txg_sync  pfn:03b96
[44484.728453] BUG: Bad page state in process txg_sync  pfn:03b97
[57405.711551] BUG: Bad page state in process ksoftirqd/1  pfn:a3245
[57405.748179] BUG: Bad page state in process ksoftirqd/1  pfn:a3246
[57405.806216] BUG: Bad page state in process ksoftirqd/1  pfn:a3247

**Comment by f-s** [comment]
@devZer0

I have the very similar setup via iScsi (identical versions of OS, kernel, module, etc.) and your error: Bad page state etc.

**Comment by behlendorf** [comment]
Closing.  This should be resolved in the 0.7 series.

**Comment by f-s** [comment]
Hi, running zfs.x86_64 0.7.5-1.el7_3 still get this:

`[Sa Feb  3 23:53:58 2018] BUG: Bad page state in process swapper/5  pfn:02934
[Sa Feb  3 23:53:58 2018] page:ffffea00000a4d00 count:0 mapcount:-1 mapping:          (null) index:0x0
[Sa Feb  3 23:53:58 2018] page flags: 0x1fffff00008000(tail)
[Sa Feb  3 23:53:58 2018] page dumped because: nonzero mapcount
[Sa Feb  3 23:53:58 2018] Modules linked in: zfs(POE) zunicode(POE) zavl(POE) icp(POE) zcommon(POE) znvpair(POE) spl(OE) sd_mod crc_t10dif crct10dif_generic crct10dif_common dm_switch dm_queue_length dm_multipath iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi xenfs xen_privcmd ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security iptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter edac_mce_amd edac_core ppdev joydev sg parport_pc parport i2c_piix4 pcspkr nfsd nfs_acl lockd grace auth_rpcgss
[Sa Feb  3 23:53:58 2018]  binfmt_misc sunrpc ip_tables xfs libcrc32c sr_mod cdrom ata_generic pata_acpi bochs_drm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm drm ata_piix xen_netfront xen_blkfront libata i2c_core serio_raw floppy dm_mirror dm_region_hash dm_log dm_mod
[Sa Feb  3 23:53:58 2018] CPU: 5 PID: 0 Comm: swapper/5 Tainted: P           OE  ------------   3.10.0-693.17.1.el7.x86_64 #1
[Sa Feb  3 23:53:58 2018] Hardware name: Xen HVM domU, BIOS 4.7.4-1.15 01/16/2018
[Sa Feb  3 23:53:58 2018] Call Trace:
[Sa Feb  3 23:53:58 2018]  <IRQ>  [<ffffffff816a6071>] dump_stack+0x19/0x1b
[Sa Feb  3 23:53:58 2018]  [<ffffffff816a16ef>] bad_page.part.75+0xdc/0xf9
[Sa Feb  3 23:53:58 2018]  [<ffffffff8118ca7d>] free_pages_prepare+0x16d/0x190
[Sa Feb  3 23:53:58 2018]  [<ffffffff8118cdc9>] __free_pages_ok+0x19/0xc0
[Sa Feb  3 23:53:58 2018]  [<ffffffff8118ce8b>] free_compound_page+0x1b/0x20
[Sa Feb  3 23:53:58 2018]  [<ffffffff816a28aa>] __put_compound_page+0x1f/0x22
[Sa Feb  3 23:53:58 2018]  [<ffffffff816a2a13>] put_compound_page+0x166/0x174
[Sa Feb  3 23:53:58 2018]  [<ffffffff81192275>] put_page+0x45/0x50
[Sa Feb  3 23:53:58 2018]  [<ffffffff81574cdf>] skb_release_data+0x8f/0x140
[Sa Feb  3 23:53:58 2018]  [<ffffffff81574db4>] skb_release_all+0x24/0x30
[Sa Feb  3 23:53:58 2018]  [<ffffffff81574dd2>] __kfree_skb+0x12/0x20
[Sa Feb  3 23:53:58 2018]  [<ffffffff81587b2e>] net_tx_action+0x8e/0x230
[Sa Feb  3 23:53:58 2018]  [<ffffffff8109275f>] __do_softirq+0xef/0x280
[Sa Feb  3 23:53:58 2018]  [<ffffffff816bd3ac>] call_softirq+0x1c/0x30
[Sa Feb  3 23:53:58 2018]  [<ffffffff8102d405>] do_softirq+0x65/0xa0
[Sa Feb  3 23:53:58 2018]  [<ffffffff81092ae5>] irq_exit+0x105/0x110
[Sa Feb  3 23:53:58 2018]  [<ffffffff813eae55>] xen_evtchn_do_upcall+0x35/0x50
[Sa Feb  3 23:53:58 2018]  [<ffffffff816bd702>] xen_hvm_callback_vector+0x232/0x240
[Sa Feb  3 23:53:58 2018]  <EOI>  [<ffffffff816ad8e6>] ? native_safe_halt+0x6/0x10
[Sa Feb  3 23:53:58 2018]  [<ffffffff816ad71e>] default_idle+0x1e/0xc0
[Sa Feb  3 23:53:58 2018]  [<ffffffff810346be>] amd_e400_idle+0x4e/0x110
[Sa Feb  3 23:53:58 2018]  [<ffffffff81034f06>] arch_cpu_idle+0x26/0x30
[Sa Feb  3 23:53:58 2018]  [<ffffffff810e9aba>] cpu_startup_entry+0x14a/0x1c0
[Sa Feb  3 23:53:58 2018]  [<ffffffff81051b96>] start_secondary+0x1d6/0x250
`

**Comment by behlendorf** [comment]
@f-s thanks for posting.  Can you please open a new issue describing your iscsi setup including software versions.

**Comment by f-s** [comment]
@behlendorf  Sorry, I am no longer using the 0.7.5-1.el7_3.
