### ISSUE TITLE
lock order inversion between zvol_open() and dsl_pool_sync()...zvol_rename_minors()

### ISSUE THREAD

**Issue by bprotopopov** [zfsonlinux/zfs#3681]
There appears to be a problem with the following two code paths executed concurrently:

1) resulting from the zfs rename on zvol snapshot, taking place in txg_sync_thread()

 #0 [ffff8802a6e7ba20] schedule at ffffffff815299d0
 #1 [ffff8802a6e7baf8] __mutex_lock_slowpath at ffffffff8152b3a6
 #2 [ffff8802a6e7bb68] mutex_lock at ffffffff8152aecb
 #3 [ffff8802a6e7bb88] zvol_rename_minors at ffffffffa02fe634 [zfs]
 #4 [ffff8802a6e7bbd8] dsl_dir_rename_sync at ffffffffa027c04d [zfs]
 #5 [ffff8802a6e7bc48] dsl_sync_task_sync at ffffffffa02850f2 [zfs]
 #6 [ffff8802a6e7bc78] dsl_pool_sync at ffffffffa027d31b [zfs]
 #7 [ffff8802a6e7bcf8] spa_sync at ffffffffa0293587 [zfs]
 #8 [ffff8802a6e7bdc8] txg_sync_thread at ffffffffa02a890b [zfs]
 #9 [ffff8802a6e7beb8] thread_generic_wrapper at ffffffffa0169978 [spl]
#10 [ffff8802a6e7bee8] kthread at ffffffff8109e78e
#11 [ffff8802a6e7bf48] kernel_thread at ffffffff8100c28a

2) resulting from opening zvol for I/O
 #0 [ffff88020e53d9b8] schedule at ffffffff815299d0
 #1 [ffff88020e53da90] cv_wait_common at ffffffffa0171e65 [spl]
 #2 [ffff88020e53db20] __cv_wait at ffffffffa0171f75 [spl]
 #3 [ffff88020e53db30] rrw_enter_read at ffffffffa028df7b [zfs]
 #4 [ffff88020e53db60] rrw_enter at ffffffffa028e0d0 [zfs]
 #5 [ffff88020e53db70] dsl_pool_config_enter at ffffffffa027c24d [zfs]
 #6 [ffff88020e53db80] dsl_pool_hold at ffffffffa027c2da [zfs]
 #7 [ffff88020e53dbc0] dmu_objset_own at ffffffffa025e1a0 [zfs]
 #8 [ffff88020e53dc20] zvol_open at ffffffffa02fd4fb [zfs]
 #9 [ffff88020e53dc90] __blkdev_get at ffffffff811cbc4e
#10 [ffff88020e53dcf0] blkdev_get at ffffffff811cbf70
#11 [ffff88020e53dd00] blkdev_open at ffffffff811cbff1
#12 [ffff88020e53dd30] __dentry_open at ffffffff8118b1ba
#13 [ffff88020e53dd90] nameidata_to_filp at ffffffff8118b524
#14 [ffff88020e53ddb0] do_filp_open at ffffffff811a12d0
#15 [ffff88020e53df20] do_sys_open at ffffffff8118af77
#16 [ffff88020e53df70] sys_open at ffffffff8118b080
#17 [ffff88020e53df80] system_call_fastpath at ffffffff8100b0f2

The first code path takes dsl pool config lock, then tries to take zvol_state_lock, while the second, takes the zvol_state_lock, and then tries to get the dsl pool config lock. 

It is interesting that zvol_first_open() called from zvol_open() takes care to obtain spa_namespace_lock, and fails if it cannot, in order to avoid the locking order inversion between spa_namespace_lock and the zvol_state_lock. 

Yet the txg_sync_thread does not seem to hold the spa_namespace_lock when calling dsl_pool_sync() and further, before trying to get the zvol_state_lock. That is why I believe this defensive check is not effective in this particular case.

**Comment by bprotopopov** [comment]
I am seriously considering performing zvol_*_minor* related functions invoked from dsl_dataset.c, spa.c, and zfs_ioctl.c, through a taskq, in order to isolate it from any sort of locking conditions in the callers.

**Comment by behlendorf** [comment]
@bprotopopov what about changing the mutex to a rwlock.  The `zvol_state_lock` is there to primarily protect against addition and removal from the list.  For places like `zvol_rename_minors` where the list is just traversed it would be safe to use a read lock.  A proper mutex to lock the individual `zvol_state_t` member during modification would probably be a good idea as well.

**Comment by bprotopopov** [comment]
@behlendorf I believe the zvol_first_open would then have to take the rwlock as a writer whereas the txg_sync_thread would take is as a reader, still resulting in the same deadlock, or am I missing something?

I have prototyped the asynchronous (in a taskq) zvol *minor* operations, and I think the code is much simplified as far as the analysis of the possible deadlocks. I also think with this approach, there is no longer a need to try-lock the spa_namespace_lock in the zvol_open() path (because everybody now takes the zvol_state_lock first and then other locks). Given that the udev-related side effects of the *minor* operations are asynchronous as well, would this approach seem like a more straightforward way to get things done?

**Comment by behlendorf** [comment]
@bprotopopov perhaps the race would be smaller but I think your right.  It would still exist.  I'm definitely not opposed to doing the minor creation asynchronously I was just tossing out another possible idea.  I'd love to see your patch for this once your happy with it.

In fact, what would be ideal is if you could build up a small patch stack with this change and your other zvol improvements.  Then we could get them all reviewed in one go and merged.

**Comment by bprotopopov** [comment]
@behlendorf sure thing

**Comment by bprotopopov** [comment]
Hope to be done by end of week

**Comment by bprotopopov** [comment]
@behlendorf, hope you can help, what is the proper way to build SPL and ZFS to enable asserts and other debug checks ?

I did make distclean, ./autogen.sh, ./configure --enable-debug, make rpm-utils && make rpm-kmod, and yum localinstall the RPMs for SPL first, then the same thing for ZFS. 

Yet I get a panic 
...
SPLError: 2477:0:(list.h:77:list_create()) ASSERTION(size >= offset + sizeof(list_node_t)) failed
SPLError: 2477:0:(list.h:77:list_create()) SPL PANIC
SPL: Showing stack for process 2477
Pid: 2477, comm: modprobe Tainted: P           ---------------    2.6.32-504.23.4.el6.x86_64 #1
Call Trace:
 [<ffffffffa02d5676>] ? spl_debug_dumpstack+0x46/0x60 [spl]
 [<ffffffffa02d6dd1>] ? spl_debug_bug+0x81/0xd0 [spl]
 [<ffffffffa02e65aa>] ? spl_PANIC+0xba/0xf0 [spl]
 [<ffffffffa02de171>] ? kmem_alloc_debug+0x251/0x490 [spl]
 [<ffffffffa02de6e1>] ? spl_kmem_cache_create+0x331/0xf50 [spl]
 [<ffffffffa02df9ef>] ? __thread_create+0x13f/0x390 [spl]
 [<ffffffff8152aebe>] ? mutex_lock+0x1e/0x50
 [<ffffffffa0451140>] ? zfs_znode_cache_constructor+0x0/0x1b0 [zfs]
 [<ffffffffa04355a0>] ? spl__init+0x0/0x20 [zfs]
 [<ffffffffa0471508>] ? zvol_init+0x88/0x290 [zfs]
 [<ffffffffa04355a0>] ? spl__init+0x0/0x20 [zfs]
 [<ffffffffa04355a0>] ? spl__init+0x0/0x20 [zfs]
 [<ffffffffa0434ab2>] ? _init+0x22/0xb10 [zfs]
 [<ffffffffa04355a0>] ? spl__init+0x0/0x20 [zfs]
 [<ffffffffa04355b3>] ? spl__init+0x13/0x20 [zfs]
 [<ffffffff8100204c>] ? do_one_initcall+0x3c/0x1d0
 [<ffffffff810c0181>] ? sys_init_module+0xe1/0x250
 [<ffffffff8100b0f2>] ? system_call_fastpath+0x16/0x1b

What am I missing ? 
Should I do make && make install instead of using RPMs ?

**Comment by behlendorf** [comment]
I'm not sure I follow the question. Passing - - enable-debug as you did will enable the assertions and it looks like your hitting one so that issue will need to be resolved.

**Comment by bprotopopov** [comment]
Well the assertion looks like mismatch of type sizes in SPL and ZFS modules, e.g. as if one is build with and one without debug support.

Thanks for confirming the procedure, it must be something in my environment.

Typos courtesy of my iPhone

On Sep 18, 2015, at 6:57 PM, Brian Behlendorf <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure I follow the question. Passing - - enable-debug as you did will enable the assertions and it looks like your hitting one so that issue will need to be resolved.

-

**Comment by bprotopopov** [comment]
@behlendorf, wanted to clarify regarding the other zvol improvements you mentioned to be included with this bugfix; I can only think of the zvol minors scalability issue (#2217); I rebased that fix as well and will put it the pull request shortly. 

Please let me know if that's what you meant.

**Comment by behlendorf** [comment]
Thanks for linking to your patches and working on this.  I think this improvement will help us close out a lot of long standing issues. I took a quick look at the patch and I have a few questions.

* Why is a necessary to create a taskq per-pool on-demand rather than global one at module load?  That definitely complicates the code and I'm not sure what advantage is has over a single global taskq in zvol.c.  Are you concerned a deadlock is possible if multiple pools are sharing the same taskq?  Or do you feel you'll need more threads when a system contains many pools.  If it's the latter I'd suggest just using TASKQ_DYNAMIC and allowing a large number of threads to be created if they're needed.

* It feels to me like the `make_async_arg` arg logic should be pulled in to `zvol_async_dispatch`.  That would allow all the helper functions to simplified.

* KM_SLEEP can now be used safely, KM_PUSHPAGE isn't required.

* Did you resolve your ASSERT issue?

**Comment by bprotopopov** [comment]
Hi, @behlendorf, 
I am still refining the code a bit; to answer your questions:
1) taskq per pool - I was trying to make the minor-related actions for different pools independent; thinking more about this, this might be an overkill, since the implementations take the zvol_state_lock which is global across the pools. I don't mind reworking the code with a single queue and TASKQ_DYNAMIC perhaps
2) I will look into that as well - I have no preference
3) perhaps because I was testing with the older code first, I did see the warnings about using KM_SLEEP in the sync context, so I looked elsewhere in zvol.c code, and I saw KM_PUSHPAGE being used exclusively, so, I followed the example - again, no preference here - do you think I should change to KM_SLEEP ?
4) I did resolve the asset due to a programming error I am not willing to discuss in public :)

**Comment by bprotopopov** [comment]
Hi, @behlendorf,

sorry for the confusion, so I remembered why a taskq per pool (barring limitations of concurrency due to the zvol_state_lock) - the taskqs must be single-threaded to guarantee ordering or request processing, and it felt a bit unsettling to limit all the minor-related work for all the pools to a single thread. 

At present, the minor-related work can originate from many user contexts, and at least some of that processing happens concurrently (e.g. dmu_objset_find() - the actual reading from disk). So, I did not want to serialize I/O for multiple pools because that could result in various undesirable dependencies between pools (e.g. hung I/O on one pool hanging minor processing on other pools, etc.). I am not sure how to achieve this concurrency while guaranteeing the ordering of request processing without multiple queues.

It also seemed that for a single pool, it should be OK to have a single thread executing requests sequentially, since the consecutive dmu_objset_find()s will likely co-benefit from I/O caching. In my testing, I did not notice any issues with performance.

**Comment by bprotopopov** [comment]
@behlendorf, I have moved the make_async_arg() logic into zvol_async_dispatch(). I held off on KM_SLEEP vs. MK_PUSHPAGE, and I think it is a good idea to keep a queue per pool as discussed above. What's your take ?

**Comment by behlendorf** [comment]
@bprotopopov I see, that makes sense.  For example, we wouldn't want it to be possible for a minor removal to potentially be handled before its matching minor create so we're limited to a single thread to keep things simple and sequential.  I suspect a single thread for the entire system would be more than enough but it's completely reasonable to create one per-pool just in case.  However, in that case I'd suggest hanging the taskq directly off the spa_t, creating it right away in `spa_activate()`, and the destroying it in `spa_deactivate()` to keep things simple.  You'll need to decide if it's worth the added complexity.

The KM_SLEEP change is safe to make so I'd go ahead with it.  If it wasn't nothing would work in the latest code!

**Comment by bprotopopov** [comment]
@behlendorf, clarification: should I replace all KM_PUSHPAGE with KM_SLEEP in zvol.c ?

**Comment by bprotopopov** [comment]
@behlendorf, I looked into following your advice regarding creating queues in spa_activate(); the function is expected to succeed (no return value), yet taskq_create() could return NULL - many places in the code check for non-NUL return. So, I could make taskq creation ''best effort" and log a WARNING message if failed to create.

**Comment by bprotopopov** [comment]
I think it will be extremely rare if we cannot create a taskq at pool activation, and if we can't there are other more pressing issues to attend to.

**Comment by bprotopopov** [comment]
So, if one creates task queues in spa_activate(), one late has to get at those queues at work dispatch time. One simple way of doing so (spa_open()) seems to deadlock (again) in zvol_rename/zvol_create paths while trying to get the spa_namespace_lock in spa_open_common().

On the other hand, I am not sure if there is a way of getting at the taskq in some other way without modifying the callers of the zvol\*minor\*() functions. I have the commits shown above. 

The original code with creation of taskqs on demand dealt with this explicitly by keeping a list of queues in for opened pools. Getting those queues on demand seems to be problematic.

**Comment by behlendorf** [comment]
> should I replace all KM_PUSHPAGE with KM_SLEEP in zvol.c ?

Yes.

> I think it will be extremely rare if we cannot create a taskq at pool activation

Right, it should be exceptionally unlikely.  And in fact this assumption is already made by `spa_create_zio_taskqs()` which is called by `spa_activate()`.  

> Getting those queues on demand seems to be problematic.

I assumed the relevant spa_t point would already be available for all the zvol*minor*() callers.  If it is then passing it as an augment seems entirely reasonable to me and is what I had in mind.  As for `spa_open()` we should avoid using that if possible, they route leads to more locking headaches and deadlocks as you discovered.

**Comment by bprotopopov** [comment]
OK, I can surely change the zvol\*minor\*() signatures to include the spa_t * pointer.

**Comment by bprotopopov** [comment]
This is the latest code that seems to balance the aded complexity with ease of deadlock analysis. It is split it two commits to simplify testing.

**Comment by behlendorf** [comment]
@bprotopopov OK, when your happy with it go ahead and open a pull request and we'll try and get some more eyes on it.

**Comment by bprotopopov** [comment]
Done

Typos courtesy of my iPhone

On Sep 24, 2015, at 12:34 PM, Brian Behlendorf <notifications@github.com<mailto:notifications@github.com>> wrote:


@bprotopopov<https://github.com/bprotopopov> OK, when your happy with it go ahead and open a pull request and we'll try and get some more eyes on it.

-

**Comment by beloncfy** [comment]
This issue still remains unresolved, I just encountered this error last night on ZoL 0.7.11 during send and receive, this is a full SSD system and running CentOS 7.5 x64.

**Comment by bprotopopov** [comment]
It seems to me that the right direction here is to move the minor management code outside of any external locking domains; 

@behlendorf, what do you think about running minor management tasks in sinple threads the nstead if pool tasks ?

**Comment by behlendorf** [comment]
Adding a dedicated thread would be fine, but it's not clear to me from the stacks above that actually would resolve the issue.  We're already do this all asynchronously in a taskq thread and in most cases not blocking waiting.  Could you explain further what you had in mind?

**Comment by bprotopopov** [comment]
@behlendorf, I am referring to the pool config lock taken prior to running minor management code. An external thread would not need to do that and the lock order inversion would not occur unless i am missing something.

**Comment by behlendorf** [comment]
Could you propose a patch with what your proposing.  I think that would probably be clearest.

**Comment by bprotopopov** [comment]
Will try to get to this as soon as i can.

**Comment by bprotopopov** [comment]
@beloncfy, could you please clarify how do you see a clear evidence of a deadlock (between the two contexts whose traces are shown)?

**Comment by beloncfy** [comment]
> @beloncfy, could you please clarify how do you see a clear evidence of a deadlock (between the two contexts whose traces are shown)?

It was zero io read and write to my zfs and my server load average were increased to > 200 without any CPU usage, the zfs list command were hanging there as well. 

It happened few times on my other servers as well with different version of ZoL. 

I guest it was triggered by the zfs receive, my servers were doing send and receive quite aggressive (every 2 minutes) and running concurrently (more than 5 volumes simultaneously). It has some VM running on it.

I have tried to reduced the send and receive frequency to 20 minutes and the concurrency to 1 volume per job, and so far so good.
