### ISSUE TITLE
Kernel Oops on 32-bit ARM

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#4048]
[ 5259.711586] Unable to handle kernel NULL pointer dereference at virtual address 00000048
[ 5259.711600] pgd = c0004000
[ 5259.711609] [00000048] *pgd=00000000
[ 5259.711624] Internal error: Oops: 17 [#1] SMP ARM
[ 5259.711632] Modules linked in: xt_tcpudp ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_raw ip6table_filter ip6_tables iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_raw iptable_filter ip_tables x_tables cmac ecb snd_soc_snow snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd soundcore uvcvideo videobuf2_vmalloc videobuf2_memops btmrvl_sdio mwifiex_sdio btmrvl videobuf2_core mwifiex v4l2_common videodev bluetooth cfg80211 media s5p_sss zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) zlib_deflate ipv6
[ 5259.711891] CPU: 3 PID: 484 Comm: kswapd0 Tainted: P           O    4.3.0-1.el7.armv5tel #1
[ 5259.711898] Hardware name: SAMSUNG EXYNOS (Flattened Device Tree)
[ 5259.711905] task: e063e900 ti: e04c8000 task.ti: e04c8000
[ 5259.712227] PC is at arc_kmem_reap_now+0x64/0xec [zfs]
[ 5259.712243] LR is at __wake_up_bit+0x20/0x54
[ 5259.712252] pc : [<bf114d3c>]    lr : [<c0054b40>]    psr: 00000113
sp : e04c9d90  ip : e04c9d50  fp : 0000008a
[ 5259.712263] r10: 00002001  r9 : bf302b08  r8 : bf2e2b08
[ 5259.712271] r7 : e04d0d00  r6 : e04d0d00  r5 : 00000000  r4 : 00007000
[ 5259.712279] r3 : e04d0b00  r2 : 00000000  r1 : 00000000  r0 : 00000000
[ 5259.712289] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 5259.712297] Control: 10c5387d  Table: 259b006a  DAC: 00000051
[ 5259.712306] Process kswapd0 (pid: 484, stack limit = 0xe04c8210)
[ 5259.712315] Stack: (0xe04c9d90 to 0xe04ca000)
[ 5259.712324] 9d80:                                     ffffffff 00008007 00000000 e04c9df8
[ 5259.712335] 9da0: bf26ea80 00000000 c066240c bf11afbc 00000000 bf1edad0 00008007 00000080
[ 5259.712344] 9dc0: 00000000 c00add48 e04c9e1c e04c9e18 00000000 00000080 00000056 00000000
[ 5259.712354] 9de0: 00000000 00000000 0000015c 000000d0 00000000 0001024c 000000d0 00000080
[ 5259.712363] 9e00: 00000000 00000000 c0697500 c0697500 e04c9f04 0000002f c0697810 00000000
[ 5259.712373] 9e20: 00000004 00000000 00000001 c00afcc0 00000000 c004fbcc 00000000 00000000
[ 5259.712384] 9e40: dc7e1400 0001024c 00000000 e04c9f00 00000000 00000008 00000000 e04c8000
[ 5259.712394] 9e60: 000008c1 00000001 00000000 00000000 00000000 00000000 00000481 00000000
[ 5259.712405] 9e80: 00000000 0000003f 00000041 00000481 e04c9e90 e04c9e90 e04c9e98 e04c9e98
[ 5259.712414] 9ea0: e04c9ea0 e04c9ea0 e063e900 c06970c0 00000001 00000000 c0697500 00000000
[ 5259.712424] 9ec0: 0000044a c06977bc e063e900 c00b0938 c000a608 ffffffff 00000000 000004a0
[ 5259.712433] 9ee0: 00000000 00000001 c0662418 c0662414 00000001 00000000 e04c8000 00000001
[ 5259.712442] 9f00: 00000641 000008c1 000000d0 00000000 00000000 00000000 00000009 00000007
[ 5259.712452] 9f20: 00000057 0000002f c00b031c e060e700 00000000 c06970c0 c00b031c 00000000
[ 5259.712461] 9f40: 00000000 00000000 00000000 c003c280 0420804c 00000000 c066b930 c06970c0
[ 5259.712471] 9f60: 00000000 00000000 dead4ead ffffffff ffffffff e04c9f74 e04c9f74 00000000
[ 5259.712481] 9f80: 00000000 dead4ead ffffffff ffffffff e04c9f90 e04c9f90 e04c9fac e060e700
[ 5259.712490] 9fa0: c003c1a4 00000000 00000000 c000edf8 00000000 00000000 00000000 00000000
[ 5259.712499] 9fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 5259.712508] 9fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[ 5259.712706] [<bf114d3c>] (arc_kmem_reap_now [zfs]) from [<bf11afbc>] (arc_shrinker_func_scan_objects+0xb8/0x1ac [zfs])
[ 5259.712787] [<bf11afbc>] (arc_shrinker_func_scan_objects [zfs]) from [<c00add48>] (shrink_slab.part.0.constprop.8+0x1b0/0x260)
[ 5259.712803] [<c00add48>] (shrink_slab.part.0.constprop.8) from [<c00afcc0>] (shrink_zone+0x5e4/0x6e4)
[ 5259.712814] [<c00afcc0>] (shrink_zone) from [<c00b0938>] (kswapd+0x61c/0x820)
[ 5259.712830] [<c00b0938>] (kswapd) from [<c003c280>] (kthread+0xdc/0xf0)
[ 5259.712846] [<c003c280>] (kthread) from [<c000edf8>] (ret_from_fork+0x14/0x3c)
[ 5259.712860] Code: e7945008 e1550003 0a000002 e1a00005 (e5951048) 
[ 5259.712919] ---[ end trace 58e3248830d2802c ]---
[ 5259.759073] Unable to handle kernel NULL pointer dereference at virtual address 00000048
[ 5259.759090] pgd = dcfd0000
[ 5259.759099] [00000048] *pgd=00000000
[ 5259.759115] Internal error: Oops: 5 [#2] SMP ARM
[ 5259.759123] Modules linked in: xt_tcpudp ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_raw ip6table_filter ip6_tables iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_raw iptable_filter ip_tables x_tables cmac ecb snd_soc_snow snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd soundcore uvcvideo videobuf2_vmalloc videobuf2_memops btmrvl_sdio mwifiex_sdio btmrvl videobuf2_core mwifiex v4l2_common videodev bluetooth cfg80211 media s5p_sss zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) zlib_deflate ipv6
[ 5259.759391] CPU: 0 PID: 4239 Comm: systemd-journal Tainted: P      D    O    4.3.0-1.el7.armv5tel #1
[ 5259.759400] Hardware name: SAMSUNG EXYNOS (Flattened Device Tree)
[ 5259.759409] task: e0553c00 ti: dcfa0000 task.ti: dcfa0000
[ 5259.759772] PC is at arc_kmem_reap_now+0x64/0xec [zfs]
[ 5259.759784] LR is at __wake_up_bit+0x20/0x54
[ 5259.759794] pc : [<bf114d3c>]    lr : [<c0054b40>]    psr: 00000113
sp : dcfa1c08  ip : dcfa1bc8  fp : 00000098
[ 5259.759803] r10: 00001fe0  r9 : bf302b08  r8 : bf2e2b08
[ 5259.759812] r7 : e04d0d00  r6 : e04d0d00  r5 : 00000000  r4 : 00007000
[ 5259.759820] r3 : e04d0b00  r2 : 00000000  r1 : 00000000  r0 : 00000000
[ 5259.759830] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 5259.759838] Control: 10c5387d  Table: 3cfd006a  DAC: 00000051
[ 5259.759846] Process systemd-journal (pid: 4239, stack limit = 0xdcfa0210)
[ 5259.759854] Stack: (0xdcfa1c08 to 0xdcfa2000)
[ 5259.759864] 1c00:                   ffffffff 00007f82 00000000 dcfa1c70 bf26ea80 00000000
[ 5259.759874] 1c20: c066240c bf11afbc 00000000 bf1edad0 00007f82 00000080 00000000 c00add48
[ 5259.759884] 1c40: dcfa1c94 dcfa1c90 00000000 00000080 0000001e 00000000 00000000 00000000
[ 5259.759893] 1c60: 0000007c 000200da 00000000 0001020d 000200da 00000080 00000000 00000000
[ 5259.759903] 1c80: c0697500 c0697500 dcfa1d74 00000036 c0697810 00000000 00000004 00000000
[ 5259.759912] 1ca0: 00000020 c00afcc0 000002cb 00000000 00000000 00000000 00000000 0001020d
[ 5259.759921] 1cc0: 00000000 dcfa1df8 00000000 00000017 00000000 dcfa0000 00000020 00000001
[ 5259.759931] 1ce0: 00000000 00000000 00000000 00000000 e135202c 00000000 00000000 0000001f
[ 5259.759941] 1d00: 00000020 e135202c dcfa1d08 dcfa1d08 dcfa1d10 dcfa1d10 dcfa1d18 dcfa1d18
[ 5259.759951] 1d20: de1dc100 c0697500 c0697d84 c0662420 0000001b 00000000 00000002 00000001
[ 5259.759961] 1d40: 00000000 c00b0254 000002dc c00a721c 000000c0 000200da c0697d80 0000000c
[ 5259.759971] 1d60: c0697d94 00000000 00000001 00000002 60000113 00000020 000200da 00000000
[ 5259.759980] 1d80: 00000000 00000000 0000000a 00000007 0000001f 00000036 00000000 000200da
[ 5259.759989] 1da0: dcfa0000 000000c0 00000000 00000000 00000001 00000000 00000000 c00a7918
[ 5259.759999] 1dc0: 00000000 dcfa1df4 dcfa1df3 dcfa1dc8 00000000 00000040 00000000 00000050
[ 5259.760008] 1de0: 000000c0 00000000 00000010 00000002 006d3480 00000000 00001572 c042b8ec
[ 5259.760017] 1e00: 00000000 c00bd98c c0697d80 00000000 c0697500 00000001 00000002 00000002
[ 5259.760027] 1e20: c9dfd000 c514faa8 b0efb000 00000000 c9dfd3ec dcfd0000 00000000 e0e35f80
[ 5259.760037] 1e40: c9dfd000 c00c0ebc 00000001 c0665140 20000193 c042b8ec 80000193 c042b8ec
[ 5259.760046] 1e60: 00000587 00000055 000000fb 000003ec dcfd2c38 14da126c 00000000 e0553c48
[ 5259.760056] 1e80: dd77f0c0 001b46e9 00000000 c004819c 00000001 e0f10900 0000232d dcfa1fb0
[ 5259.760066] 1ea0: b0efb000 00000055 e0553c00 e0e35f80 00000817 e0e35fc4 c514faa8 c001a184
[ 5259.760077] 1ec0: a09b3275 000004c8 00f1ef33 00000000 e134f190 00000000 b0efa000 00000000
[ 5259.760087] 1ee0: 00000800 00000000 de1dc100 00000817 b0efb000 c066cde4 dcfa1fb0 10c5387d
[ 5259.760097] 1f00: 00000000 beffcda0 b6efd928 c00092b8 dc490a00 c042b8fc e0553c00 c003fe2c
[ 5259.760108] 1f20: c000a608 ffffffff 00000000 c003cf48 dba5a018 e0553c00 e134f140 de1dc100
[ 5259.760118] 1f40: e0e35f80 e076d500 c0668e84 c0665140 dcfa1f8c c0427914 c0662568 00000000
[ 5259.760126] 1f60: e0c10000 00000001 00000000 dcfa0000 dcfa1fb0 00000000 10c5387d 00000000
[ 5259.760136] 1f80: dcfa0000 beffcda0 dcfa1f9c c0427b98 dcfa1fa0 dcfa0000 b6efd928 b6d6fb88
[ 5259.760144] 1fa0: 20000010 ffffffff 10c5387d c00132fc b0745008 00000000 0088b000 b0efb000
[ 5259.760153] 1fc0: 7f5b4d70 ffffffff 7f5b4d70 b6fc6eb8 7f5b4cb8 00000000 beffcda0 b6efd928
[ 5259.760162] 1fe0: 00000000 beffcd18 b6ef43e0 b6d6fb88 20000010 ffffffff 00000000 00000000
[ 5259.760351] [<bf114d3c>] (arc_kmem_reap_now [zfs]) from [<bf11afbc>] (arc_shrinker_func_scan_objects+0xb8/0x1ac [zfs])
[ 5259.760428] [<bf11afbc>] (arc_shrinker_func_scan_objects [zfs]) from [<c00add48>] (shrink_slab.part.0.constprop.8+0x1b0/0x260)
[ 5259.760443] [<c00add48>] (shrink_slab.part.0.constprop.8) from [<c00afcc0>] (shrink_zone+0x5e4/0x6e4)
[ 5259.760456] [<c00afcc0>] (shrink_zone) from [<c00b0254>] (try_to_free_pages+0x494/0x55c)
[ 5259.760474] [<c00b0254>] (try_to_free_pages) from [<c00a7918>] (__alloc_pages_nodemask+0x28c/0x74c)
[ 5259.760493] [<c00a7918>] (__alloc_pages_nodemask) from [<c00c0ebc>] (handle_mm_fault+0x208/0xc7c)
[ 5259.760512] [<c00c0ebc>] (handle_mm_fault) from [<c001a184>] (do_page_fault+0x12c/0x32c)
[ 5259.760526] [<c001a184>] (do_page_fault) from [<c00092b8>] (do_DataAbort+0x34/0xb4)
[ 5259.760537] [<c00092b8>] (do_DataAbort) from [<c00132fc>] (__dabt_usr+0x3c/0x40)
[ 5259.760545] Exception stack(0xdcfa1fb0 to 0xdcfa1ff8)
[ 5259.760553] 1fa0:                                     b0745008 00000000 0088b000 b0efb000
[ 5259.760563] 1fc0: 7f5b4d70 ffffffff 7f5b4d70 b6fc6eb8 7f5b4cb8 00000000 beffcda0 b6efd928
[ 5259.760571] 1fe0: 00000000 beffcd18 b6ef43e0 b6d6fb88 20000010 ffffffff
[ 5259.760582] Code: e7945008 e1550003 0a000002 e1a00005 (e5951048) 
[ 5259.760621] ---[ end trace 58e3248830d2802d ]---
[ 5259.853561] systemd-journald[14179]: File /run/log/journal/4e24bd32ade844409612a9d6bbc40e5d/system.journal corrupted or uncleanly shut down, renaming and replacing.
[ 5259.996657] systemd-journald[14179]: Received request to flush runtime journal from PID 1
[ 5344.599944] Unable to handle kernel NULL pointer dereference at virtual address 00000048
[ 5344.599956] pgd = c5e90000
[ 5344.599963] [00000048] *pgd=3cec9831, *pte=00000000, *ppte=00000000
[ 5344.599983] Internal error: Oops: 17 [#3] SMP ARM
[ 5344.599990] Modules linked in: xt_tcpudp ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_raw ip6table_filter ip6_tables iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_raw iptable_filter ip_tables x_tables cmac ecb snd_soc_snow snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd soundcore uvcvideo videobuf2_vmalloc videobuf2_memops btmrvl_sdio mwifiex_sdio btmrvl videobuf2_core mwifiex v4l2_common videodev bluetooth cfg80211 media s5p_sss zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) zlib_deflate ipv6
[ 5344.600201] CPU: 1 PID: 14203 Comm: as Tainted: P      D    O    4.3.0-1.el7.armv5tel #1
[ 5344.600208] Hardware name: SAMSUNG EXYNOS (Flattened Device Tree)
[ 5344.600216] task: d0e91400 ti: c5e54000 task.ti: c5e54000
[ 5344.600526] PC is at arc_kmem_reap_now+0x64/0xec [zfs]
[ 5344.600537] LR is at __wake_up_bit+0x20/0x54
[ 5344.600545] pc : [<bf114d3c>]    lr : [<c0054b40>]    psr: 00000113
sp : c5e55c08  ip : c5e55bc8  fp : 0000008a
[ 5344.600553] r10: 00001fe9  r9 : bf302b08  r8 : bf2e2b08
[ 5344.600560] r7 : e04d0d00  r6 : e04d0d00  r5 : 00000000  r4 : 00007000
[ 5344.600566] r3 : e04d0b00  r2 : 00000000  r1 : 00000000  r0 : 00000000
[ 5344.600575] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 5344.600583] Control: 10c5387d  Table: 25e9006a  DAC: 00000051
[ 5344.600590] Process as (pid: 14203, stack limit = 0xc5e54210)
[ 5344.600597] Stack: (0xc5e55c08 to 0xc5e56000)
[ 5344.600607] 5c00:                   ffffffff 00007fa5 00000000 c5e55c70 bf26ea80 00000000
[ 5344.600616] 5c20: c066240c bf11afbc 00000000 bf1edad0 00007fa5 00000080 00000000 c00add48
[ 5344.600627] 5c40: c5e55c94 c5e55c90 00000000 00000080 0000001a 00000000 00000000 00000000
[ 5344.600639] 5c60: 0000006c 000200da 00000000 00010142 000200da 00000080 00000000 00000000
[ 5344.600650] 5c80: c0697500 c0697500 c5e55d74 00000005 c0697810 00000000 00000004 00000000
[ 5344.600661] 5ca0: 00000010 c00afcc0 004bc3a0 00000000 00000000 00000000 004bc3a0 00010142
[ 5344.600671] 5cc0: 00000000 c5e55df8 00000000 00000002 00000000 c5e54000 00000020 00000001
[ 5344.600682] 5ce0: 00000000 00000000 00000000 00000000 e135e02c 00000000 00000000 0000000f
[ 5344.600694] 5d00: 00000010 e135e02c c5e55d08 c5e55d08 c5e55d10 c5e55d10 c5e55d18 c5e55d18
[ 5344.600706] 5d20: e135b190 c0697500 c0697d84 c0662420 0000000e 00000000 00000002 00000001
[ 5344.600717] 5d40: 00000000 c00b0254 000002dc c00a721c 000000c0 000200da c0697d80 0000000c
[ 5344.600727] 5d60: c0697d94 00000000 00000001 00000002 60000113 00000020 000200da 00000000
[ 5344.600736] 5d80: 00000000 00000000 0000000b 00000007 0000001b 00000005 e135b140 000200da
[ 5344.600744] 5da0: c5e54000 000000c0 00000000 00000000 00000001 00000000 00000000 c00a7918
[ 5344.600753] 5dc0: 00000000 c5e55df4 c5e55df3 c5e55dc8 00000000 00000040 00000000 00000050
[ 5344.600763] 5de0: 000000c0 00000000 00000010 00000002 006d3480 00000000 00001558 c042b8ec
[ 5344.600771] 5e00: 00000000 c00bd98c c0697d80 00000000 c0697500 00000001 00000002 00000002
[ 5344.600780] 5e20: c549f000 c6206948 007f4000 00000000 c549f7d0 c5e90000 00000000 e0e36840
[ 5344.600789] 5e40: c549f000 c00c0ebc c5e55e80 e0559800 e0e1b210 c006b67c 565723dc 3a501850
[ 5344.600798] 5e60: 00000003 00000055 000001f4 000007d0 c5e90018 c00f3388 dafe67d0 d9603600
[ 5344.600806] 5e80: e0e1b210 00001000 00000000 00000000 dafe67d0 c00f4b28 565723dc c5e55fb0
[ 5344.600815] 5ea0: 007f4474 00000055 d0e91400 e0e36840 00000817 e0e36884 c6206948 c001a184
[ 5344.600823] 5ec0: 00000001 00000007 c0437e80 c5e55f0c 00000000 00000000 007f348c 00000000
[ 5344.600832] 5ee0: 00000800 00000000 0009a5e4 00000817 007f4474 c066cde4 c5e55fb0 10c5387d
[ 5344.600841] 5f00: 00002710 007f4470 b6e654fc c00092b8 00000000 00000000 c5e55f0c 00000001
[ 5344.600849] 5f20: d0bce500 00000000 00000000 00000000 00000000 d0bce500 00001000 d0bce508
[ 5344.600857] 5f40: 00000001 dafe67d0 00000000 00000000 0009a5e4 c00de270 00000000 00000000
[ 5344.600866] 5f60: 00001000 00000000 00000000 d0bce500 d0bce500 00001000 0009a5e4 c00de9ac
[ 5344.600875] 5f80: 00000000 00000000 00001000 00000000 ffffffff ffffffff 00000003 b6d8ff10
[ 5344.600883] 5fa0: 60000010 ffffffff 10c5387d c00132fc 00000fe9 00000fe9 00000000 00001b91
[ 5344.600893] 5fc0: 00000001 007f3490 b6e654cc 007f3488 007838e8 00002710 007f4470 b6e654fc
[ 5344.600901] 5fe0: 00000062 bec8f038 b6d91f0c b6d8ff10 60000010 ffffffff 00000000 00000000
[ 5344.601070] [<bf114d3c>] (arc_kmem_reap_now [zfs]) from [<bf11afbc>] (arc_shrinker_func_scan_objects+0xb8/0x1ac [zfs])
[ 5344.601144] [<bf11afbc>] (arc_shrinker_func_scan_objects [zfs]) from [<c00add48>] (shrink_slab.part.0.constprop.8+0x1b0/0x260)
[ 5344.601157] [<c00add48>] (shrink_slab.part.0.constprop.8) from [<c00afcc0>] (shrink_zone+0x5e4/0x6e4)
[ 5344.601167] [<c00afcc0>] (shrink_zone) from [<c00b0254>] (try_to_free_pages+0x494/0x55c)
[ 5344.601184] [<c00b0254>] (try_to_free_pages) from [<c00a7918>] (__alloc_pages_nodemask+0x28c/0x74c)
[ 5344.601200] [<c00a7918>] (__alloc_pages_nodemask) from [<c00c0ebc>] (handle_mm_fault+0x208/0xc7c)
[ 5344.601218] [<c00c0ebc>] (handle_mm_fault) from [<c001a184>] (do_page_fault+0x12c/0x32c)
[ 5344.601230] [<c001a184>] (do_page_fault) from [<c00092b8>] (do_DataAbort+0x34/0xb4)
[ 5344.601241] [<c00092b8>] (do_DataAbort) from [<c00132fc>] (__dabt_usr+0x3c/0x40)
[ 5344.601247] Exception stack(0xc5e55fb0 to 0xc5e55ff8)
[ 5344.601256] 5fa0:                                     00000fe9 00000fe9 00000000 00001b91
[ 5344.601264] 5fc0: 00000001 007f3490 b6e654cc 007f3488 007838e8 00002710 007f4470 b6e654fc
[ 5344.601272] 5fe0: 00000062 bec8f038 b6d91f0c b6d8ff10 60000010 ffffffff
[ 5344.601282] Code: e7945008 e1550003 0a000002 e1a00005 (e5951048) 
[ 5344.601293] ---[ end trace 58e3248830d2802e ]---
[ 6350.895147] Unable to handle kernel NULL pointer dereference at virtual address 00000048
[ 6350.895158] pgd = c8cec000
[ 6350.895165] [00000048] *pgd=29a84831, *pte=00000000, *ppte=00000000
[ 6350.895183] Internal error: Oops: 17 [#4] SMP ARM
[ 6350.895190] Modules linked in: xt_tcpudp ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_raw ip6table_filter ip6_tables iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_raw iptable_filter ip_tables x_tables cmac ecb snd_soc_snow snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd soundcore uvcvideo videobuf2_vmalloc videobuf2_memops btmrvl_sdio mwifiex_sdio btmrvl videobuf2_core mwifiex v4l2_common videodev bluetooth cfg80211 media s5p_sss zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) zlib_deflate ipv6
[ 6350.895370] CPU: 3 PID: 8548 Comm: bash Tainted: P      D    O    4.3.0-1.el7.armv5tel #1
[ 6350.895377] Hardware name: SAMSUNG EXYNOS (Flattened Device Tree)
[ 6350.895384] task: e063a300 ti: c8810000 task.ti: c8810000
[ 6350.895672] PC is at arc_kmem_reap_now+0x64/0xec [zfs]
[ 6350.895682] LR is at __wake_up_bit+0x20/0x54
[ 6350.895690] pc : [<bf114d3c>]    lr : [<c0054b40>]    psr: 00000013
sp : c8811e00  ip : c8811dc0  fp : 0000fe4a
[ 6350.895697] r10: 00001fce  r9 : bf302b08  r8 : bf2e2b08
[ 6350.895704] r7 : e04d0d00  r6 : e04d0d00  r5 : 00000000  r4 : 00007000
[ 6350.895710] r3 : e04d0b00  r2 : 00000000  r1 : 00000000  r0 : 00000000
[ 6350.895717] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 6350.895724] Control: 10c5387d  Table: 28cec06a  DAC: 00000051
[ 6350.895730] Process bash (pid: 8548, stack limit = 0xc8810210)
[ 6350.895737] Stack: (0xc8811e00 to 0xc8812000)
[ 6350.895745] 1e00: ffffffff 00007f39 00000000 c8811e68 bf26ea80 00016b5d c066240c bf11afbc
[ 6350.895754] 1e20: 00000000 bf1edad0 00007f39 00000080 00016b5d c00add48 e2aa4d80 e294eec0
[ 6350.895761] 1e40: 00000000 00000080 0000fe30 00000000 e0144400 00000000 00000fa0 000000d0
[ 6350.895769] 1e60: 00000000 000003e8 000000d0 00000080 00000000 00000000 e0144044 00000000
[ 6350.895777] 1e80: c066e63c 00000001 b6f0f000 c8811f80 00000002 00000002 00000000 c00adee8
[ 6350.895785] 1ea0: c06da5a8 c0121acc c8811f80 00000001 e0c1a000 c012db00 c8811f80 b6f0f000
[ 6350.895793] 1ec0: 00000002 00000002 c012db1c b6f0f000 d680ba00 c8811f80 00000002 b6f0f000
[ 6350.895801] 1ee0: 00000000 c012db2c 00000001 b6f0f000 00000002 c00ddc38 c8811fb0 10c5387d
[ 6350.895808] 1f00: 00000000 00000000 bebc8a2c c000936c 00000000 c8811f18 00000000 0000000a
[ 6350.895816] 1f20: bebc8a2c c00f5e8c 00000001 d680ba00 c8811f80 00000002 00000000 c00585a8
[ 6350.895824] 1f40: d680ba00 b6f0f000 c8811f80 00000002 00000002 c00de33c d680ba00 b6f0f000
[ 6350.895832] 1f60: 00000002 00000000 00000000 d680ba00 d680ba00 00000002 b6f0f000 c00dea28
[ 6350.895839] 1f80: 00000002 00000000 00000002 00000002 b6f0f000 b6e74b38 00000004 c000ef04
[ 6350.895847] 1fa0: c8810000 c000ed40 00000002 b6f0f000 00000001 b6f0f000 00000002 00000000
[ 6350.895855] 1fc0: 00000002 b6f0f000 b6e74b38 00000004 00000002 00000002 b6f0f000 00000000
[ 6350.895863] 1fe0: 00000000 bebc894c b6d96068 b6df6b8c 60000010 00000001 00021036 01e0fa8d
[ 6350.895992] [<bf114d3c>] (arc_kmem_reap_now [zfs]) from [<bf11afbc>] (arc_shrinker_func_scan_objects+0xb8/0x1ac [zfs])
[ 6350.896059] [<bf11afbc>] (arc_shrinker_func_scan_objects [zfs]) from [<c00add48>] (shrink_slab.part.0.constprop.8+0x1b0/0x260)
[ 6350.896071] [<c00add48>] (shrink_slab.part.0.constprop.8) from [<c00adee8>] (drop_slab_node+0x1c/0x28)
[ 6350.896082] [<c00adee8>] (drop_slab_node) from [<c0121acc>] (drop_caches_sysctl_handler+0x74/0xfc)
[ 6350.896092] [<c0121acc>] (drop_caches_sysctl_handler) from [<c012db00>] (proc_sys_call_handler+0x9c/0xb8)
[ 6350.896101] [<c012db00>] (proc_sys_call_handler) from [<c012db2c>] (proc_sys_write+0x10/0x18)
[ 6350.896112] [<c012db2c>] (proc_sys_write) from [<c00ddc38>] (__vfs_write+0x28/0xd0)
[ 6350.896121] [<c00ddc38>] (__vfs_write) from [<c00de33c>] (vfs_write+0xa4/0x148)
[ 6350.896130] [<c00de33c>] (vfs_write) from [<c00dea28>] (SyS_write+0x3c/0x7c)
[ 6350.896144] [<c00dea28>] (SyS_write) from [<c000ed40>] (ret_fast_syscall+0x0/0x3c)
[ 6350.896153] Code: e7945008 e1550003 0a000002 e1a00005 (e5951048) 
[ 6350.896162] ---[ end trace 58e3248830d2802f ]---
[ 6372.937607] Unable to handle kernel NULL pointer dereference at virtual address 00000048
[ 6372.937619] pgd = db564000
[ 6372.937626] [00000048] *pgd=3c57a831, *pte=00000000, *ppte=00000000
[ 6372.937646] Internal error: Oops: 17 [#5] SMP ARM
[ 6372.937653] Modules linked in: xt_tcpudp ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_raw ip6table_filter ip6_tables iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_raw iptable_filter ip_tables x_tables cmac ecb snd_soc_snow snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd soundcore uvcvideo videobuf2_vmalloc videobuf2_memops btmrvl_sdio mwifiex_sdio btmrvl videobuf2_core mwifiex v4l2_common videodev bluetooth cfg80211 media s5p_sss zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) zlib_deflate ipv6
[ 6372.937866] CPU: 0 PID: 14927 Comm: bash Tainted: P      D    O    4.3.0-1.el7.armv5tel #1
[ 6372.937873] Hardware name: SAMSUNG EXYNOS (Flattened Device Tree)
[ 6372.937880] task: de099e00 ti: c6db0000 task.ti: c6db0000
[ 6372.938195] PC is at arc_kmem_reap_now+0x64/0xec [zfs]
[ 6372.938205] LR is at __wake_up_bit+0x20/0x54
[ 6372.938212] pc : [<bf114d3c>]    lr : [<c0054b40>]    psr: 00000013
sp : c6db1e00  ip : c6db1dc0  fp : 000118a0
[ 6372.938219] r10: 00002314  r9 : bf302b08  r8 : bf2e2b08
[ 6372.938226] r7 : e04d0d00  r6 : e04d0d00  r5 : 00000000  r4 : 00007000
[ 6372.938232] r3 : e04d0b00  r2 : 00000000  r1 : 00000000  r0 : 00000000
[ 6372.938239] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 6372.938245] Control: 10c5387d  Table: 3b56406a  DAC: 00000051
[ 6372.938252] Process bash (pid: 14927, stack limit = 0xc6db0210)
[ 6372.938258] Stack: (0xc6db1e00 to 0xc6db2000)
[ 6372.938267] 1e00: ffffffff 00008c50 00000000 c6db1e68 bf26ea80 000000ec c066240c bf11afbc
[ 6372.938275] 1e20: 00000000 bf1edad0 00008c50 00000080 000000ec c00add48 e2aa4d80 e294eec0
[ 6372.938283] 1e40: 00000000 00000080 00011858 00000000 e0144400 00000000 00000fa0 000000d0
[ 6372.938291] 1e60: 00000000 000003e8 000000d0 00000080 00000000 00000000 e0144044 00000000
[ 6372.938299] 1e80: c066e63c 00000001 b6ff7000 c6db1f80 00000002 00000002 00000000 c00adee8
[ 6372.938307] 1ea0: c06da5a8 c0121acc c6db1f80 00000001 e0c1a000 c012db00 c6db1f80 b6ff7000
[ 6372.938315] 1ec0: 00000002 00000002 c012db1c b6ff7000 d0457800 c6db1f80 00000002 b6ff7000
[ 6372.938322] 1ee0: 00000000 c012db2c 00000001 b6ff7000 00000002 c00ddc38 c4abaf60 00000301
[ 6372.938330] 1f00: 00000000 000001bc 00000000 00000000 00000000 c6db1f18 00000000 0000000a
[ 6372.938338] 1f20: be81aa2c c00f5e8c 00000001 d0457800 c6db1f80 00000002 00000000 c00585a8
[ 6372.938346] 1f40: d0457800 b6ff7000 c6db1f80 00000002 00000002 c00de33c d0457800 b6ff7000
[ 6372.938353] 1f60: 00000002 00000000 00000000 d0457800 d0457800 00000002 b6ff7000 c00dea28
[ 6372.938361] 1f80: 00000002 00000000 00000002 00000002 b6ff7000 b6f5bb38 00000004 c000ef04
[ 6372.938369] 1fa0: c6db0000 c000ed40 00000002 b6ff7000 00000001 b6ff7000 00000002 00000000
[ 6372.938376] 1fc0: 00000002 b6ff7000 b6f5bb38 00000004 00000002 00000002 b6ff7000 00000000
[ 6372.938384] 1fe0: 00000000 be81a94c b6e7d068 b6eddb8c 60000010 00000001 00021236 01e15ef3
[ 6372.938507] [<bf114d3c>] (arc_kmem_reap_now [zfs]) from [<bf11afbc>] (arc_shrinker_func_scan_objects+0xb8/0x1ac [zfs])
[ 6372.938575] [<bf11afbc>] (arc_shrinker_func_scan_objects [zfs]) from [<c00add48>] (shrink_slab.part.0.constprop.8+0x1b0/0x260)
[ 6372.938586] [<c00add48>] (shrink_slab.part.0.constprop.8) from [<c00adee8>] (drop_slab_node+0x1c/0x28)
[ 6372.938597] [<c00adee8>] (drop_slab_node) from [<c0121acc>] (drop_caches_sysctl_handler+0x74/0xfc)
[ 6372.938608] [<c0121acc>] (drop_caches_sysctl_handler) from [<c012db00>] (proc_sys_call_handler+0x9c/0xb8)
[ 6372.938617] [<c012db00>] (proc_sys_call_handler) from [<c012db2c>] (proc_sys_write+0x10/0x18)
[ 6372.938628] [<c012db2c>] (proc_sys_write) from [<c00ddc38>] (__vfs_write+0x28/0xd0)
[ 6372.938637] [<c00ddc38>] (__vfs_write) from [<c00de33c>] (vfs_write+0xa4/0x148)
[ 6372.938646] [<c00de33c>] (vfs_write) from [<c00dea28>] (SyS_write+0x3c/0x7c)
[ 6372.938659] [<c00dea28>] (SyS_write) from [<c000ed40>] (ret_fast_syscall+0x0/0x3c)
[ 6372.938669] Code: e7945008 e1550003 0a000002 e1a00005 (e5951048) 
[ 6372.942198] ---[ end trace 58e3248830d28030 ]---

This is several Oopses that happened in quick succession. The machine is still running and remains responsive, but echo 3 > /proc/sys/vm/drop_caches now causes another Oops to happen every time it is run.

The ZFS/SPL is 0.6.5.3 with the patch for spl issue #2505 applied.

**Comment by tuxoko** [comment]
This should be fixed in master https://github.com/zfsonlinux/zfs/commit/d0c614ecf9eb0b5f5c5d75316c2faeff63e03c4e

**Comment by gordan-bobic** [comment]
I can confirm that  commit https://github.com/zfsonlinux/zfs/commit/d0c614ecf9eb0b5f5c5d75316c2faeff63e03c4e doesn't fix this. I applied the patch, rebuild zfs modules, rebooted, and I still just got the following:

[ 3267.702370] Unable to handle kernel NULL pointer dereference at virtual address 00000048
[ 3267.702383] pgd = db848000
[ 3267.702390] [00000048] *pgd=3e5c9831, *pte=00000000, *ppte=00000000
[ 3267.702409] Internal error: Oops: 17 [#2] SMP ARM
[ 3267.702417] Modules linked in: xt_tcpudp ipt_REJECT nf_reject_ipv4 xt_conntrack ip6_tables iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_raw iptable_filter ip_tables x_tables cmac ecb snd_soc_snow ext4 mbcache jbd2 snd_soc_i2s snd_soc_idma snd_soc_s3c_dma snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd soundcore uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_core v4l2_common videodev mwifiex_sdio media mwifiex cfg80211 btmrvl_sdio btmrvl bluetooth s5p_sss zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) zlib_deflate
[ 3267.702597] CPU: 3 PID: 29034 Comm: cc1plus Tainted: P      D    O    4.3.0-3.el7.armv5tel #1
[ 3267.702604] Hardware name: SAMSUNG EXYNOS (Flattened Device Tree)
[ 3267.702611] task: ca415a00 ti: ca74e000 task.ti: ca74e000
[ 3267.702918] PC is at arc_kmem_reap_now+0x64/0xec [zfs]
[ 3267.702927] LR is at __wake_up_bit+0x20/0x54
[ 3267.702936] pc : [<bf0abd3c>]    lr : [<c0054b40>]    psr: 00000013
sp : ca74fc80  ip : ca74fc40  fp : 000000a1
[ 3267.702943] r10: 00002bf8  r9 : bf299b08  r8 : bf279b08
[ 3267.702950] r7 : e00dac00  r6 : e00dac00  r5 : 00000000  r4 : 00007000
[ 3267.702956] r3 : e00dab00  r2 : 00000000  r1 : 00000000  r0 : 00000000
[ 3267.702964] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 3267.702971] Control: 10c5387d  Table: 3b84806a  DAC: 00000051
[ 3267.702979] Process cc1plus (pid: 29034, stack limit = 0xca74e210)
[ 3267.702986] Stack: (0xca74fc80 to 0xca750000)
[ 3267.702994] fc80: ffffffff 0000afe0 00000000 ca74fce8 bf205a80 00000000 c060640c bf0b1fbc
[ 3267.703003] fca0: 00000000 bf184ad8 0000afe0 00000080 00000000 c00add48 ca74fd0c ca74fd08
[ 3267.703011] fcc0: 00000000 00000080 00000065 00000000 00000000 00000000 000000c8 000200d2
[ 3267.703020] fce0: 00000000 0000ade1 000200d2 00000080 00000000 00000000 c063b300 c063b300
[ 3267.703028] fd00: ca74fdec 00000006 c063b610 00000000 00000004 00000000 00000011 c00afcc0
[ 3267.703036] fd20: 000008f9 dce55300 00000000 00000000 00000000 0000ade1 00000000 ca74fe70
[ 3267.703044] fd40: 00000000 00000006 00000000 ca74e000 00000020 00000001 00000000 00000000
[ 3267.703052] fd60: 00000000 00000000 f5257d14 00000000 00000000 00000019 00000011 f5257d14
[ 3267.703060] fd80: ca74fd80 ca74fd80 ca74fd88 ca74fd88 ca74fd90 ca74fd90 dcab5c00 c063b300
[ 3267.703069] fda0: c063bb84 c0606420 00000020 00000000 00000001 00000001 00000000 c00b0254
[ 3267.703077] fdc0: 000002dc c00a721c 00000040 000200d2 c063bb80 0000000c c063bb94 00000000
[ 3267.703086] fde0: 00000001 e1373140 ca415a48 00000020 000200d2 00000000 00000000 00000000
[ 3267.703094] fe00: 0000000a 00000007 00000032 00000006 ca415a00 000200d2 ca74e000 00000040
[ 3267.703102] fe20: 00000000 00000000 00000001 00000000 00000000 c00a7918 00000000 ca74fe6c
[ 3267.703110] fe40: ca74fe6b c0609140 ca74fe84 00000040 00000000 00000050 00000040 00000000
[ 3267.703118] fe60: 00000010 00000000 0089f900 00000000 00000824 c00f3388 d089f900 00000006
[ 3267.703126] fe80: c063bb80 00000000 c063b300 00000001 00000000 00000001 d64bc700 00000000
[ 3267.703134] fea0: d64bc700 00000000 c609d300 ca74ff0c 00000009 ca62e4d8 ca74e000 c00e4778
[ 3267.703142] fec0: ca833782 e17e52c0 000000d8 ca62e400 e1373190 00000000 00000000 c609d300
[ 3267.703150] fee0: ca74ff80 00001000 b6fbb000 00000000 00a2e771 c00ddcb4 00001000 10c5387d
[ 3267.703158] ff00: 00bfdfec b6fbb000 00001000 00000001 00000000 00001000 ca74ff04 00000001
[ 3267.703166] ff20: c609d300 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3267.703174] ff40: c609d300 b6fbb000 ca74ff80 00001000 00001000 c00de33c c609d300 b6fbb000
[ 3267.703182] ff60: 00001000 00000000 00000000 c609d300 c609d300 00001000 b6fbb000 c00dea28
[ 3267.703190] ff80: 00000000 00000000 00001000 00001000 b6fbb000 b6deab38 00000004 c000ef04
[ 3267.703198] ffa0: ca74e000 c000ed40 00001000 b6fbb000 00000001 b6fbb000 00001000 00000000
[ 3267.703206] ffc0: 00001000 b6fbb000 b6deab38 00000004 00001000 00001000 b6fbb000 00a2e771
[ 3267.703214] ffe0: 00000000 bec71e54 b6d0c068 b6d6cb8c 60000010 00000001 00020236 01e02e2e
[ 3267.703350] [<bf0abd3c>] (arc_kmem_reap_now [zfs]) from [<bf0b1fbc>] (arc_shrinker_func_scan_objects+0xb8/0x1ac [zfs])
[ 3267.703421] [<bf0b1fbc>] (arc_shrinker_func_scan_objects [zfs]) from [<c00add48>] (shrink_slab.part.0.constprop.8+0x1b0/0x260)
[ 3267.703432] [<c00add48>] (shrink_slab.part.0.constprop.8) from [<c00afcc0>] (shrink_zone+0x5e4/0x6e4)
[ 3267.703442] [<c00afcc0>] (shrink_zone) from [<c00b0254>] (try_to_free_pages+0x494/0x55c)
[ 3267.703456] [<c00b0254>] (try_to_free_pages) from [<c00a7918>] (__alloc_pages_nodemask+0x28c/0x74c)
[ 3267.703471] [<c00a7918>] (__alloc_pages_nodemask) from [<c00e4778>] (pipe_write+0x1e0/0x3cc)
[ 3267.703482] [<c00e4778>] (pipe_write) from [<c00ddcb4>] (__vfs_write+0xa4/0xd0)
[ 3267.703490] [<c00ddcb4>] (__vfs_write) from [<c00de33c>] (vfs_write+0xa4/0x148)
[ 3267.703500] [<c00de33c>] (vfs_write) from [<c00dea28>] (SyS_write+0x3c/0x7c)
[ 3267.703513] [<c00dea28>] (SyS_write) from [<c000ed40>] (ret_fast_syscall+0x0/0x3c)
[ 3267.703523] Code: e7945008 e1550003 0a000002 e1a00005 (e5951048) 
[ 3267.703534] ---[ end trace dc546e8d1acc9b3e ]---

**Comment by tuxoko** [comment]
@gordan-bobic 
You need to check if the loaded module is indeed the new built module.
If zfs module is loaded during initrd. You need to also rebuilt the initrd with new zfs.ko

**Comment by gordan-bobic** [comment]
I did, it is, and I did, in that order.

**Comment by tuxoko** [comment]
@gordan-bobic 
That doesn't seems right.
```PC is at arc_kmem_reap_now+0x64/0xec [zfs]```
This line is the same before and after, which should not happen if the patch is built and loaded correctly.

Can you objdump the function ```arc_kmem_reap_now``` before and after the patch.

**Comment by gordan-bobic** [comment]
Hmm, I just checked the new and old zfs.ko and they are exactly the same size, which is odd. I wonder if _ILP32 is not getting defined...

**Comment by behlendorf** [comment]
Or the `zio_buf_cache` array global isn't being NULL initialized which is causing the NULL check to fail.  Dropping a printk in there for debugging would make things clear.

**Comment by tuxoko** [comment]
```zio_buf_cache``` is global so it must be NULL. The oops also show it's NULL. The problem is @gordan-bobic not building the binary properly with dkms.

I'm not sure what's the proper way to patch a dkms'ed source. What I always do is to purge the zfs stuffs in ```/var/lib/dkms```, patch the source in ```/usr/src/zfs-0.x.y```, and do dkms add. Otherwise, dkms might use the stale source in ```/var/lib/dkms```

**Comment by gordan-bobic** [comment]
There is only one set of sources, as least as set up by DKMS on EL7: in /usr/src/zfs-0.6.5.3.
/var/lib/dkms/zfs-0.6.5.3/source is a symlink to /usr/src/zfs-0.6.5.3.

I am not sure what else could be going on. I'll try rebuilding the modules without dkms and see if that produces different results.

**Comment by tuxoko** [comment]
@gordan-bobic 
On my ubuntu, there's a ```build``` besides ```source``` which contains a copy of the source.

**Comment by gordan-bobic** [comment]
On EL7 that is not the case. I have just verified that the only copy of arc.c on the machine is in fact patched. I have purged all traces of previous build directories and modules for the current kernel and am rebuilding the modules. Will report back shortly, but since the last build was made with the same sources, I expect the same result. If that is the case, it really would imply that _ILP32 is not defined on armv5tel/GCC 4.8.x.

**Comment by behlendorf** [comment]
@gordan-bobic you're absolutely right, it was entirely possible for _ILP32 and _LP64 not to be defined on some arm, powerpc, and sparc builds.  Things were correct on x86 and x86_64 bit systems which is why it worked for @tuxoko.

I've opened #4082 with a fix but as you're well aware the test coverage on non-x86 systems leaves something we to desired.  There is an ARMv7 builder in the mix but that's it.

On a related note I just recently [followed up](http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-December/023993.html) on your zfs-discuss post from June 2015 asking what could be done to improve the test coverage of the buildbot.  Bottom line it's now much easier for us to do that.  If you can offer up a machine with internet access I'd like to pursue adding it as builder.  It should be straight forward.

**Comment by tuxoko** [comment]
@behlendorf But if _ILP32 is not defined, why would there be NULL in zio_buf_cache?
https://github.com/behlendorf/zfs/blob/master/module/zfs/zio.c#L120

@gordan-bobic Can you dump gcc macros with this command?
```gcc -dM -E - < /dev/null```.

**Comment by behlendorf** [comment]
@tuxoko on 32-bit systems kmem_cache_create() will return NULL when requesting caches with very large objects.

**Comment by gordan-bobic** [comment]
@tuxoko:
$ gcc -dM -E - < /dev/null
#define __DBL_MIN_EXP__ (-1021)
#define __HQ_FBIT__ 15
#define __UINT_LEAST16_MAX__ 65535
#define __ARM_SIZEOF_WCHAR_T 32
#define __ATOMIC_ACQUIRE 2
#define __SFRACT_IBIT__ 0
#define __FLT_MIN__ 1.1754943508222875e-38F
#define __UFRACT_MAX__ 0XFFFFP-16UR
#define __UINT_LEAST8_TYPE__ unsigned char
#define __DQ_FBIT__ 63
#define __INTMAX_C(c) c ## LL
#define __ULFRACT_FBIT__ 32
#define __SACCUM_EPSILON__ 0x1P-7HK
#define __CHAR_BIT__ 8
#define __USQ_IBIT__ 0
#define __UINT8_MAX__ 255
#define __ACCUM_FBIT__ 15
#define __WINT_MAX__ 4294967295U
#define __USFRACT_FBIT__ 8
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __SIZE_MAX__ 4294967295U
#define __ARM_ARCH_ISA_ARM 1
#define __WCHAR_MAX__ 4294967295U
#define __LACCUM_IBIT__ 32
#define __DBL_DENORM_MIN__ ((double)4.9406564584124654e-324L)
#define __GCC_ATOMIC_CHAR_LOCK_FREE 1
#define __FLT_EVAL_METHOD__ 0
#define __unix__ 1
#define __LLACCUM_MAX__ 0X7FFFFFFFFFFFFFFFP-31LLK
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 1
#define __FRACT_FBIT__ 15
#define __UINT_FAST64_MAX__ 18446744073709551615ULL
#define __SIG_ATOMIC_TYPE__ int
#define __UACCUM_FBIT__ 16
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define __ARMEL__ 1
#define __LFRACT_IBIT__ 0
#define __GNUC_PATCHLEVEL__ 3
#define __LFRACT_MAX__ 0X7FFFFFFFP-31LR
#define __UINT_FAST8_MAX__ 255
#define __DEC64_MAX_EXP__ 385
#define __INT8_C(c) c
#define __UINT_LEAST64_MAX__ 18446744073709551615ULL
#define __SA_FBIT__ 15
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __FRACT_MAX__ 0X7FFFP-15R
#define __UFRACT_FBIT__ 16
#define __ARM_FP 12
#define __UFRACT_MIN__ 0.0UR
#define __UINT_LEAST8_MAX__ 255
#define __GCC_ATOMIC_BOOL_LOCK_FREE 1
#define __UINTMAX_TYPE__ long long unsigned int
#define __LLFRACT_EPSILON__ 0x1P-63LLR
#define __linux 1
#define __DEC32_EPSILON__ 1E-6DF
#define __CHAR_UNSIGNED__ 1
#define __UINT32_MAX__ 4294967295U
#define __ULFRACT_MAX__ 0XFFFFFFFFP-32ULR
#define __TA_IBIT__ 64
#define __LDBL_MAX_EXP__ 1024
#define __WINT_MIN__ 0U
#define __linux__ 1
#define __ULLFRACT_MIN__ 0.0ULLR
#define __SCHAR_MAX__ 127
#define __WCHAR_MIN__ 0U
#define __INT64_C(c) c ## LL
#define __DBL_DIG__ 15
#define __ARM_NEON_FP 4
#define __GCC_ATOMIC_POINTER_LOCK_FREE 1
#define __LLACCUM_MIN__ (-0X1P31LLK-0X1P31LLK)
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 4
#define __USACCUM_IBIT__ 8
#define __USER_LABEL_PREFIX__ 
#define __STDC_HOSTED__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LFRACT_MIN__ (-0.5LR-0.5LR)
#define __HA_IBIT__ 8
#define __TQ_IBIT__ 0
#define __FLT_EPSILON__ 1.1920928955078125e-7F
#define __APCS_32__ 1
#define __USFRACT_IBIT__ 0
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __FRACT_MIN__ (-0.5R-0.5R)
#define __DEC32_MAX__ 9.999999E96DF
#define __DA_IBIT__ 32
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __INT32_MAX__ 2147483647
#define __UQQ_FBIT__ 8
#define __SIZEOF_LONG__ 4
#define __UACCUM_MAX__ 0XFFFFFFFFP-16UK
#define __STDC_IEC_559__ 1
#define __STDC_ISO_10646__ 201103L
#define __UINT16_C(c) c
#define __DECIMAL_DIG__ 17
#define __LFRACT_EPSILON__ 0x1P-31LR
#define __ULFRACT_MIN__ 0.0ULR
#define __gnu_linux__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __ULACCUM_IBIT__ 32
#define __UACCUM_EPSILON__ 0x1P-16UK
#define __GNUC__ 4
#define __ULLACCUM_MAX__ 0XFFFFFFFFFFFFFFFFP-32ULLK
#define __HQ_IBIT__ 0
#define __FLT_HAS_DENORM__ 1
#define __SIZEOF_LONG_DOUBLE__ 8
#define __ARM_ARCH_5T__ 1
#define __BIGGEST_ALIGNMENT__ 8
#define __DQ_IBIT__ 0
#define __DBL_MAX__ ((double)1.7976931348623157e+308L)
#define __ULFRACT_IBIT__ 0
#define __INT_FAST32_MAX__ 2147483647
#define __DBL_HAS_INFINITY__ 1
#define __ACCUM_IBIT__ 16
#define __DEC32_MIN_EXP__ (-94)
#define __THUMB_INTERWORK__ 1
#define __LACCUM_MAX__ 0X7FFFFFFFFFFFFFFFP-31LK
#define __INT_FAST16_TYPE__ int
#define __LDBL_HAS_DENORM__ 1
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __INT_LEAST32_MAX__ 2147483647
#define __ARM_PCS 1
#define __DEC32_MIN__ 1E-95DF
#define __ACCUM_MAX__ 0X7FFFFFFFP-15K
#define __DBL_MAX_EXP__ 1024
#define __USACCUM_EPSILON__ 0x1P-8UHK
#define __DEC128_EPSILON__ 1E-33DL
#define __SFRACT_MAX__ 0X7FP-7HR
#define __FRACT_IBIT__ 0
#define __PTRDIFF_MAX__ 2147483647
#define __UACCUM_MIN__ 0.0UK
#define __STDC_NO_THREADS__ 1
#define __UACCUM_IBIT__ 16
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __SIZEOF_SIZE_T__ 4
#define __ULACCUM_MAX__ 0XFFFFFFFFFFFFFFFFP-32ULK
#define __SIZEOF_WINT_T__ 4
#define __SA_IBIT__ 16
#define __ULLACCUM_MIN__ 0.0ULLK
#define __GXX_ABI_VERSION 1002
#define __UTA_FBIT__ 64
#define __SOFTFP__ 1
#define __FLT_MIN_EXP__ (-125)
#define __USFRACT_MAX__ 0XFFP-8UHR
#define __UFRACT_IBIT__ 0
#define __INT_FAST64_TYPE__ long long int
#define __DBL_MIN__ ((double)2.2250738585072014e-308L)
#define __LACCUM_MIN__ (-0X1P31LK-0X1P31LK)
#define __ULLACCUM_FBIT__ 32
#define __GXX_TYPEINFO_EQUALITY_INLINE 0
#define __ULLFRACT_EPSILON__ 0x1P-64ULLR
#define __DEC128_MIN__ 1E-6143DL
#define __REGISTER_PREFIX__ 
#define __UINT16_MAX__ 65535
#define __DBL_HAS_DENORM__ 1
#define __ACCUM_MIN__ (-0X1P15K-0X1P15K)
#define __SQ_IBIT__ 0
#define __UINT8_TYPE__ unsigned char
#define __UHA_FBIT__ 8
#define __NO_INLINE__ 1
#define __SFRACT_MIN__ (-0.5HR-0.5HR)
#define __UTQ_FBIT__ 128
#define __FLT_MANT_DIG__ 24
#define __VERSION__ "4.8.3 20140911 (Red Hat 4.8.3-9)"
#define __UINT64_C(c) c ## ULL
#define __ULLFRACT_FBIT__ 64
#define __FRACT_EPSILON__ 0x1P-15R
#define __ULACCUM_MIN__ 0.0ULK
#define _STDC_PREDEF_H 1
#define __UDA_FBIT__ 32
#define __LLACCUM_EPSILON__ 0x1P-31LLK
#define __GCC_ATOMIC_INT_LOCK_FREE 1
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __USFRACT_MIN__ 0.0UHR
#define __UQQ_IBIT__ 0
#define __STDC_IEC_559_COMPLEX__ 1
#define __INT32_C(c) c
#define __DEC64_EPSILON__ 1E-15DD
#define __ORDER_PDP_ENDIAN__ 3412
#define __DEC128_MIN_EXP__ (-6142)
#define __UHQ_FBIT__ 16
#define __LLACCUM_FBIT__ 31
#define __INT_FAST32_TYPE__ int
#define __UINT_LEAST16_TYPE__ short unsigned int
#define unix 1
#define __INT16_MAX__ 32767
#define __SIZE_TYPE__ unsigned int
#define __UINT64_MAX__ 18446744073709551615ULL
#define __UDQ_FBIT__ 64
#define __INT8_TYPE__ signed char
#define __ELF__ 1
#define __ULFRACT_EPSILON__ 0x1P-32ULR
#define __LLFRACT_FBIT__ 63
#define __FLT_RADIX__ 2
#define __INT_LEAST16_TYPE__ short int
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __UINTMAX_C(c) c ## ULL
#define __GNUC_RH_RELEASE__ 9
#define __SACCUM_MAX__ 0X7FFFP-7HK
#define __SIG_ATOMIC_MAX__ 2147483647
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 1
#define __VFP_FP__ 1
#define __SIZEOF_PTRDIFF_T__ 4
#define __LACCUM_EPSILON__ 0x1P-31LK
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __INT_FAST16_MAX__ 2147483647
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __USACCUM_MAX__ 0XFFFFP-8UHK
#define __SFRACT_EPSILON__ 0x1P-7HR
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MAX_10_EXP__ 38
#define __LONG_MAX__ 2147483647L
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __FLT_HAS_INFINITY__ 1
#define __unix 1
#define __USA_FBIT__ 16
#define __UINT_FAST16_TYPE__ unsigned int
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __CHAR16_TYPE__ short unsigned int
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __INT_LEAST16_MAX__ 32767
#define __DEC64_MANT_DIG__ 16
#define __INT64_MAX__ 9223372036854775807LL
#define __UINT_LEAST32_MAX__ 4294967295U
#define __SACCUM_FBIT__ 7
#define __GCC_ATOMIC_LONG_LOCK_FREE 1
#define __INT_LEAST64_TYPE__ long long int
#define __ARM_FEATURE_CLZ 1
#define __INT16_TYPE__ short int
#define __INT_LEAST8_TYPE__ signed char
#define __SQ_FBIT__ 31
#define __DEC32_MAX_EXP__ 97
#define __ARM_ARCH_ISA_THUMB 1
#define __INT_FAST8_MAX__ 127
#define __ARM_ARCH 5
#define __INTPTR_MAX__ 2147483647
#define __QQ_FBIT__ 7
#define linux 1
#define __UTA_IBIT__ 64
#define __LDBL_MANT_DIG__ 53
#define __SFRACT_FBIT__ 7
#define __SACCUM_MIN__ (-0X1P7HK-0X1P7HK)
#define __DBL_HAS_QUIET_NAN__ 1
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __INTPTR_TYPE__ int
#define __UINT16_TYPE__ short unsigned int
#define __WCHAR_TYPE__ unsigned int
#define __SIZEOF_FLOAT__ 4
#define __USQ_FBIT__ 32
#define __UINTPTR_MAX__ 4294967295U
#define __DEC64_MIN_EXP__ (-382)
#define __ULLACCUM_IBIT__ 32
#define __INT_FAST64_MAX__ 9223372036854775807LL
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __FLT_DIG__ 6
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __INT_MAX__ 2147483647
#define __LACCUM_FBIT__ 31
#define __USACCUM_MIN__ 0.0UHK
#define __UHA_IBIT__ 8
#define __INT64_TYPE__ long long int
#define __FLT_MAX_EXP__ 128
#define __UTQ_IBIT__ 0
#define __DBL_MANT_DIG__ 53
#define __INT_LEAST64_MAX__ 9223372036854775807LL
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 1
#define __DEC64_MIN__ 1E-383DD
#define __WINT_TYPE__ unsigned int
#define __UINT_LEAST32_TYPE__ unsigned int
#define __SIZEOF_SHORT__ 2
#define __ULLFRACT_IBIT__ 0
#define __LDBL_MIN_EXP__ (-1021)
#define __arm__ 1
#define __UDA_IBIT__ 32
#define __INT_LEAST8_MAX__ 127
#define __LFRACT_FBIT__ 31
#define __LDBL_MAX_10_EXP__ 308
#define __ATOMIC_RELAXED 0
#define __DBL_EPSILON__ ((double)2.2204460492503131e-16L)
#define __UINT8_C(c) c
#define __INT_LEAST32_TYPE__ int
#define __SIZEOF_WCHAR_T__ 4
#define __UINT64_TYPE__ long long unsigned int
#define __LLFRACT_MAX__ 0X7FFFFFFFFFFFFFFFP-63LLR
#define __TQ_FBIT__ 127
#define __INT_FAST8_TYPE__ signed char
#define __ULLACCUM_EPSILON__ 0x1P-32ULLK
#define __UHQ_IBIT__ 0
#define __LLACCUM_IBIT__ 32
#define __DBL_DECIMAL_DIG__ 17
#define __DEC_EVAL_METHOD__ 2
#define __TA_FBIT__ 63
#define __UDQ_IBIT__ 0
#define __ORDER_BIG_ENDIAN__ 4321
#define __ACCUM_EPSILON__ 0x1P-15K
#define __UINT32_C(c) c ## U
#define __INTMAX_MAX__ 9223372036854775807LL
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLT_DENORM_MIN__ 1.4012984643248171e-45F
#define __LLFRACT_IBIT__ 0
#define __INT8_MAX__ 127
#define __UINT_FAST32_TYPE__ unsigned int
#define __CHAR32_TYPE__ unsigned int
#define __FLT_MAX__ 3.4028234663852886e+38F
#define __USACCUM_FBIT__ 8
#define __INT32_TYPE__ int
#define __SIZEOF_DOUBLE__ 8
#define __FLT_MIN_10_EXP__ (-37)
#define __UFRACT_EPSILON__ 0x1P-16UR
#define __INTMAX_TYPE__ long long int
#define __DEC128_MAX_EXP__ 6145
#define __ATOMIC_CONSUME 1
#define __GNUC_MINOR__ 8
#define __UINTMAX_MAX__ 18446744073709551615ULL
#define __DEC32_MANT_DIG__ 7
#define __HA_FBIT__ 7
#define __DBL_MAX_10_EXP__ 308
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __INT16_C(c) c
#define __STDC__ 1
#define __PTRDIFF_TYPE__ int
#define __LLFRACT_MIN__ (-0.5LLR-0.5LLR)
#define __ATOMIC_SEQ_CST 5
#define __DA_FBIT__ 31
#define __UINT32_TYPE__ unsigned int
#define __UINTPTR_TYPE__ unsigned int
#define __USA_IBIT__ 16
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __ARM_EABI__ 1
#define __DEC128_MANT_DIG__ 34
#define __LDBL_MIN_10_EXP__ (-307)
#define __SIZEOF_LONG_LONG__ 8
#define __ULACCUM_EPSILON__ 0x1P-32ULK
#define __SACCUM_IBIT__ 8
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1
#define __LDBL_DIG__ 15
#define __FLT_DECIMAL_DIG__ 9
#define __UINT_FAST16_MAX__ 4294967295U
#define __GNUC_GNU_INLINE__ 1
#define __GCC_ATOMIC_SHORT_LOCK_FREE 1
#define __ULLFRACT_MAX__ 0XFFFFFFFFFFFFFFFFP-64ULLR
#define __UINT_FAST8_TYPE__ unsigned char
#define __USFRACT_EPSILON__ 0x1P-8UHR
#define __ULACCUM_FBIT__ 32
#define __QQ_IBIT__ 0
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_RELEASE 3

@behlendorf: Thanks, I missed that post on the list. I will try to put a RedSleeve 7 machine up for the buildbot and reply on the above thread.

**Comment by tuxoko** [comment]
Yeah, it seems gcc only defines _LP64 but never define _ILP32.

**Comment by gordan-bobic** [comment]
Right. So to conclude, this issue _IS_ fixed by the following commit set:
https://github.com/zfsonlinux/zfs/commit/d0c614ecf9eb0b5f5c5d75316c2faeff63e03c4e
https://github.com/behlendorf/spl/commit/625a42172f2f625457409e4b2144e466a6377984
https://github.com/behlendorf/zfs/commit/1288d09188f108bc76c66704a93852855bdb5d4d

Given that all of the 32-bit specific code based on _ILP32 is in fact going to be ignored, I'm amazed ZoL works quite well on armv5tel as it is. I am not regularly hitting any other bugs.

What release are these likely to make it into, and is there any indication on when that release is expected to land (days/weeks/months)?

**Comment by behlendorf** [comment]
@gordan-bobic great news.  Yes, I'm a little surprised things have worked so well too.  Although, many of the checks in the code (and there aren't too many) actually check for _LP64 being defined and assume _ILP32 when it's not.

I'll get the remaining fixes in to master shortly, and we're planning for an 0.6.5.4 within weeks.  Not months.
