### ISSUE TITLE
[4.4-rcX] checking spl build directory takes forever - can't find kmod spl devel <kernel> package

### ISSUE THREAD

**Issue by philmmanjaro** [zfsonlinux/zfs#4054]
```
checking zfs config... kernel
checking for -Wno-unused-but-set-variable support... yes
checking for -Wno-bool-compare support... yes
checking kernel source directory... /usr/lib/modules/4.4.0-1-MANJARO/build
checking kernel build directory... /usr/lib/modules/4.4.0-1-MANJARO/build
checking kernel source version... 4.4.0-1-MANJARO
checking kernel file name for module symbols... Module.symvers
checking spl source directory... /usr/src/spl-0.6.5.2
checking spl build directory... /home/phil/dev/git/manjaro/repositories/extra/linux44-extramodules/spl_zfs/src/dkms/spl/0.6.5.2/build
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.

Building module:
cleaning build area...(bad exit status: 2)
make KERNELRELEASE=4.4.0-1-MANJARO...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-1-MANJARO (x86_64)
Consult /home/phil/dev/git/manjaro/repositories/extra/linux44-extramodules/spl_zfs/src/dkms/zfs/0.6.5.2/build/make.log for more information.
```

Do I miss something here? The source it finds on every other kernel also: `spl-dkms /usr/src/spl-0.6.5.2/`

**Comment by philmmanjaro** [comment]
Here is the [config.log](https://gist.github.com/philmmanjaro/3e4ecf3c24dd70567fd7).

**Comment by philmmanjaro** [comment]
Here is another try with [zfs](https://gist.github.com/philmmanjaro/063cecbaf4f7314600bc). However [spl](https://gist.github.com/philmmanjaro/947962e0237b636d6ca7) works just fine.

**Comment by philmmanjaro** [comment]
Ok, issue is within **dkms 2.2.0.3+git151023-1**. I've to check what changed here.

**Comment by dasJ** [comment]
Had the same issue, fixed it by running `# dkms autoinstall`

**Comment by jwise** [comment]
This is solved by https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836578 .

**Comment by mailinglists35** [comment]
> This is solved by https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836578

nope.

maintainer claims it's fixed but for me it's still not working for kernels 4.6 and 4.7 from jessie-backports

checking spl build directory... <- here stays for a "sleep 600" period (5 minutes)
then fails with

configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.


spl builds ok on both 4.6 and 4.7
