### ISSUE TITLE
ZFS 0.6.5.3 - zpool import after hard reboot causes kernel panic

### ISSUE THREAD

**Issue by jsosic** [zfsonlinux/zfs#4114]
Hi guys,

after loss of power, zpool won't import my pool in RW mode. I can import and back up everything with `zpool import -o readonly=on data`, but there seems to be no way to import the pool in RW mode.

I'm running latest CentOS 7 and 0.6.5.3 build through dkms from zfs yum repository.

I'm attaching kernel dmesg.txts after 1 unsuccessful import with SELinux in enforcing mode and another with SELinux in permissive mode.

I've backed up my data without any issues. Also, I've run `zdb -e -bcsvL <poolname>` and it did pass without any errors. I've read that suggestion on this blog:

http://sigtar.com/2009/10/19/opensolaris-zfs-recovery-after-kernel-panic/

I would like to set zfs_recover to 1 but don't know how to do it on Linux.
[vmcore-dmesg.txt](https://github.com/zfsonlinux/zfs/files/64691/vmcore-dmesg.txt)

**Comment by jsosic** [comment]
I just successfully mounted RW on FreeBSD 11.1 live image! :+1:  So this is definitely some kind of bug in ZFSonLinux.

I'm running scrub, and after scrub I'll retry mount in Linux.

**Comment by behlendorf** [comment]
Thanks for filing the bug report, we have a few similar reports we're still looking in too.  It's helpful to know you were able to import it under FreeBSD.

**Comment by tuxoko** [comment]
Same as #4052 #4006

**Comment by jsosic** [comment]
No problem if you need more info, I can provide... After importing on FreeBSD and after full scrub, CentOS still panicks :(

**Comment by tuxoko** [comment]
@jsosic 
Could you try booting with slub_debug.

**Comment by behlendorf** [comment]
@jsosic does it panic with the same back trace?  And did you mount all the file systems on FreeBSD?  If so that's surprising because FreeBSD should have fully processed the unlinked set which means it shouldn't need to do this again under Linux.

**Comment by jsosic** [comment]
Actually it didn't mount /home under FreeBSD live. I mounted it manually after changing mountpoint to /tmp/home, and that's the filesystem that causes panic, even under BSD. So I guess this maybe isn't a bug after all?

Is there a way to drain unlinked list to make it mount RW, or should I just drop the issue and reformat?

**Comment by jsosic** [comment]
@tuxoko as `slub_debug` in kernel cmdline?

**Comment by behlendorf** [comment]
@jsosic it's definitely a bug.  Panicing the system isn't OK except as a last resort to avoid damaging the pool, and that isn't at all the case here.  But it does sound like this isn't a bug specific to Linux which is a useful bit of information.

Based on the back trace it suggests a rw lock in memory is being damaged/overwritten which result in the hard lockup and NMI.  Booting with `slab_debug` as suggested on the kernel command line could helpful.  Or perhaps even better since I see you're running CentOS 7 install the __kernel-debug__ and __kernel-debug-devel__ packages then build ZFS against those and attempt the mount.  This will enable significantly more debugging which may shed some light on things.

**Comment by tuxoko** [comment]
```slub_debug``` with a 'u'

**Comment by behlendorf** [comment]
Whoops, yes.  I've updated by comment above.

**Comment by jsosic** [comment]
I can't build the module for -debug kernel. I changed configure script to omit the `` check, but after that I get:

`FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'debug_lockdep_rcu_enabled'`

https://gist.github.com/jsosic/ee9cb7b981691455c5a6

**Comment by tuxoko** [comment]
@jsosic 
You should change zfs license to GPL in META.

**Comment by jsosic** [comment]
```
[root@workstation ~]# cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-3.10.0-327.3.1.el7.x86_64 root=UUID=8b98f518-f569-436d-8a28-f2957c788b5c ro rd.md.uuid=8ad8ccdf:c533490b:56c658a0:b9c14623 vconsole.keymap=us rd.md.uuid=6818e408:747f67b8:0ca60b4f:7bb45061 rd.md.uuid=98f303fd:8a7167fc:50bf476a:1034435b crashkernel=auto vconsole.font=latarcyrheb-sun16 rhgb nouveau.modeset=0 rd.driver.blacklist=nouveau vga=0x361 LANG=en_US.UTF-8 ipv6.disable=1 slub_debug
[root@workstation ~]# zpool import -o readonly=on data
[root@workstation ~]# zpool status
  pool: data
 state: ONLINE
  scan: scrub repaired 0 in 0h40m with 0 errors on Thu Dec 17 02:28:27 2015
config:

	NAME                                            STATE     READ WRITE CKSUM
	data                                            ONLINE       0     0     0
	  mirror-0                                      ONLINE       0     0     0
	    ata-WDC_WD6401AALS-00L3B2_WD-WCASY7537886   ONLINE       0     0     0
	    ata-WDC_WD6401AALS-00L3B2_WD-WCASY7537788   ONLINE       0     0     0
	logs
	  mirror-1                                      ONLINE       0     0     0
	    ata-OCZ-VERTEX4_OCZ-5K69JHDS8LU2R681-part5  ONLINE       0     0     0
	    ata-OCZ-VERTEX4_OCZ-SNMU3089SDH69V8E-part5  ONLINE       0     0     0
	cache
	  ata-OCZ-VERTEX4_OCZ-SNMU3089SDH69V8E-part6    ONLINE       0     0     0
	  ata-OCZ-VERTEX4_OCZ-5K69JHDS8LU2R681-part6    ONLINE       0     0     0

errors: No known data errors
[root@workstation ~]# zfs list
NAME          USED  AVAIL  REFER  MOUNTPOINT
data          137G   440G    27K  /tmp/data
data/docker  5.82G   440G  5.82G  /tmp/docker
data/home     131G   440G   131G  /tmp/home
data/proxy     24K   440G    24K  /tmp/data/proxy
[root@workstation ~]# zpool export data
[root@workstation ~]# zpool import data
```

**Comment by tuxoko** [comment]
slub_debug didn't catch anything, that's a bummer.
I'll try to come up with some debug patch.

**Comment by jsosic** [comment]
Here's the crash of the debug kernel and zfs.ko compiled against (with patched META). Do you need slub_debug with -debug kernel also?
[vmcore-dmesg-2015-12-17-debug.txt](https://github.com/zfsonlinux/zfs/files/65997/vmcore-dmesg-2015-12-17-debug.txt)

**Comment by tuxoko** [comment]
Both doesn't seem to have useful information.
Could you try this debug patch:
https://gist.github.com/tuxoko/b98c72d79150d349b50d

**Comment by jsosic** [comment]
Here ya go:
[vmcore-dmesg-debugpatch.txt](https://github.com/zfsonlinux/zfs/files/66054/vmcore-dmesg-debugpatch.txt)

**Comment by tuxoko** [comment]
```leaf=ffff8807cb4cc000 object=1619117 blkid=0```
Ok, we are getting something.

https://github.com/zfsonlinux/zfs/blob/b815ec32b3ba04ad7307ca8945a865eec0ec766b/module/zfs/zap.c#L515
The blkid shouldn't be 0.
So it's not the spinlock been corrupted, but it's not even spinlock in the first place.
I'll have to analyze this further.

**Comment by tuxoko** [comment]
Could you do ```zdb -edddddd data/home 1619117``` and post the result.
I assume data/home is the faulted filesystem.

**Comment by jsosic** [comment]
```
Dataset data/home [ZPL], ID 42, cr_txg 22941, 131G, 904936 objects, rootbp DVA[0]=<0:2c0003a000:200> DVA[1]=<0:4100051c00:200> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=2817250L/2817250P fill=904936 cksum=dd39abbe6:4b936dce78c:db4fe6243661:1c01968681aa32

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
   1619117    1    16K    512      0    512    0.00  ZFS directory (K=inherit) (Z=inherit)
                                        168   bonus  System attributes
	dnode flags: USED_BYTES USERUSED_ACCOUNTED 
	dnode maxblkid: 0
	path	???<object#1619117>
	uid     1505
	gid     1505
	atime	Wed Dec 16 13:06:14 2015
	mtime	Wed Dec 16 16:21:39 2015
	ctime	Wed Dec 16 16:21:39 2015
	crtime	Wed Dec 16 13:06:14 2015
	gen	2814730
	mode	41777
	size	2
	parent	1619116
	links	0
	pflags	40800000145
	Fat ZAP stats:
		Pointer table:
			1 elements
			zt_blk: 0
			zt_numblks: 0
			zt_shift: 0
			zt_blks_copied: 0
			zt_nextblk: 0
		ZAP entries: 0
		Leaf blocks: 0
		Total blocks: 0
		zap_block_type: 0x0
		zap_magic: 0x0
		zap_salt: 0x0
		Leafs with 2^n pointers:
		Blocks with n*5 entries:
		Blocks n/10 full:
		Entries with n chunks:
		Buckets with n entries:
```
And it hangs there.

**Comment by tuxoko** [comment]
@jsosic 
https://gist.github.com/tuxoko/b98c72d79150d349b50d
I updated the patch, hopefully zdb can finish executing with this.

**Comment by jsosic** [comment]
Nope, still hangs at the same point. This is the `strace` of the running zdb:

```
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
futex(0x1f66058, FUTEX_WAKE_PRIVATE, 2) = 0
```

And it dumps bunch of futex syscalls on screen.

**Comment by tuxoko** [comment]
Right, thanks anyway for all the info you've got.

There's definitely something not right with this object.
This object is most likely an xattr directory.
It's dsize is 0, and every zap attribute is also 0.
It's basically an empty object.

@jsosic 
What xattr option do you use?
Use ```zfs get xattr``` when imported read only, if you don't know.

@behlendorf Do you have any idea what could have caused this?

**Comment by jsosic** [comment]
```
# zfs get xattr 
NAME               PROPERTY  VALUE  SOURCE
data               xattr     on     default
data/docker        xattr     on     default
data/home          xattr     on     default
data/home@initial  xattr     on     default
data/proxy         xattr     on     default
```

**Comment by tuxoko** [comment]
@jsosic 
If you have backed up important data, you can try #4123.
Setting module parameter ```zfs_recover=1``` and import rw, and see if things go well.
After that change back to ```zfs_recover=0``` and import rw again and see if things go well.

**Comment by behlendorf** [comment]
@tuxoko looking at `zfs_purgedir()` and I'm not positive but it looks like it _might_ be possible that if we encounter an error we could leave an empty xattr directory in the unlinked set.  This seems like something we could easily check for at the top of `zfs_purgedir()`.  Or better yet fix the ZAP code, I don't see why we couldn't safely iterate over an empty fat ZAP.

**Comment by jsosic** [comment]
Initial mount with `zfs_recover=1` (debug kernel):

```
[  242.101566] WARNING: blkid=0 passed in. (object=1619117)

[  243.705101] leaf=ffff8807d0285800 object=3 blkid=1585
[  243.708443] leaf=ffff8807d0285800 rw_enter success!
[  245.866652] leaf=ffff8807d0283000 object=3 blkid=1553
[  245.870319] leaf=ffff8807d0283000 rw_enter success!
[  245.872933] leaf=ffff8807d0283000 object=3 blkid=1553
[  245.876681] leaf=ffff8807d0283000 rw_enter success!
[  248.041340] leaf=ffff8807cfc40400 object=3 blkid=948
[  248.044600] leaf=ffff8807cfc40400 rw_enter success!
[  249.700690] leaf=ffff8807d0281c00 object=3 blkid=335
[  249.703844] leaf=ffff8807d0281c00 rw_enter success!
[  250.207977] leaf=ffff8807cf220c00 object=3 blkid=300
[  250.211064] leaf=ffff8807cf220c00 rw_enter success!
[  250.247922] SELinux: initialized (dev zfs, type zfs), uses xattr
[  250.252214] mount.zfs (3848) used greatest stack depth: 11184 bytes left
```

After this I hit `reboot`, and booted standard non-debug kernel, with vanilla ZFS (non-patched) module 0.6.5.3....
Everything seems fine so far!!! :+1: 

Thank you guys for awesome support.

I hope I did also help you with my feedback and tests! :)

**Comment by tuxoko** [comment]
@jsosic 
Thanks for all the testing, it was really helpful.

**Comment by tuxoko** [comment]
@behlendorf 
So I don't think it's error in ```zfs_purgedir``` caused this. If you look at the zdb log, the object is not exactly a fat zap. It's completely empty, meaning it doesn't even have a header block.

I think what caused this is after ```zfs_purgedir``` succeeded. We do ```dmu_free_long_range```. After that and before object removal, the system went down. So we have an empty zap object in the delete queue. I can try to simulate this behaviour and see if my theory is right.

So if my theory is right, we probably only need to put a check at ```zfs_purgedir``` for this special case. If we need to "fix" zap code to handle empty object in general, it might require much work.
