### ISSUE TITLE
ZFS raw send: kernel modules must be upgraded to receive this stream

### ISSUE THREAD

**Issue by ronnyegner** [zfsonlinux/zfs#6706]
### System information SOURCE

Distribution Name       |  Ubuntu
  ---                                  |     --- 
Distribution Version    |  17.04
Linux Kernel                 |  4.10.0-24-generic
Architecture                 | x86_64
ZFS Version                  | v0.7.0-50_g1ea8942fa
SPL Version                  | v0.7.0-12_g9df9692

### System information TARGET

Distribution Name       |  Debian
  ---                                  |     --- 
Distribution Version    |  9.1
Linux Kernel                 |  4.9.0-3-amd64
Architecture                 | x86_64
ZFS Version                  | 0.7.0-50_g1ea8942fa
SPL Version                  | 0.7.0-12_g9df9692

### Describe the problem you're observing
ZFS send/recv from a new child of an exiting encryption root fails with:
`cannot receive new filesystem stream: kernel modules must be upgraded to receive this stream`
while a newly created encryption root works.

The details:
This is the existing encryption root on SOURCE:
```
# zfs get creation,keyformat,encryption pool2/encrypt
NAME           PROPERTY    VALUE                  SOURCE
pool2/encrypt  creation    Sat Sep  2  5:56 2017  -
pool2/encrypt  keyformat   passphrase             -
pool2/encrypt  encryption  aes-256-gcm            -
```
The encryption root was (as far as i remember) created after merging #6595 

Let´s create a child and copy some data in it:

```
# zfs create pool2/encrypt/tmp
# cp -r /etc /pool2/encrypt/tmp
# zfs snapshot pool2/encrypt/tmp@transfer_1

```
The subsequent send fails:
```
zfs send -c -w pool2/encrypt/tmp@transfer_1 | ssh TARGET zfs recv -s backup/test
cannot receive new filesystem stream: kernel modules must be upgraded to receive this stream.
```
It also causes the whole pool to **corrupt** on receiving side in a way that you cannot execute any "zfs" commands anymore.

```
root@backup ~ # zfs list
Aborted
```
The culpuit is the "-s" switch here. Without it i get an error receiving but the target pool stays healthy.

```
# zfs send -c -w pool2/encrypt/tmp@transfer_1 | ssh TARGET zfs recv backup/test
cannot receive new filesystem stream: invalid backup stream
```
The ZFS dump file is 40 MB compressed and can be provided for debugging purposes.

When i create a new encryption root and a child it works:

```
# echo "password" | zfs create -o encryption=aes-256-gcm -o keyformat=passphrase pool2/newenc
# zfs create pool2/newenc/temp
# cp -r /etc /pool2/newenc/temp/
# zfs snapshot pool2/newenc/temp@transfer_1
# zfs send -c -w pool2/newenc/temp@transfer_1 | ssh TARGET zfs recv -s backup/test

```
--> No error and works successfully.

**Comment by tcaputi** [comment]
I'm not quite sure what you mean by "new" vs"existing" here. Could you elaborate more? Does this happen if you re-create everything from scratch? Are both systems using the same version of zfs?

**Comment by tcaputi** [comment]
having the zfs send file would probably be good too. Feel free to share it any way you see fit (so long as it does not have sensitive data).

**Comment by ronnyegner** [comment]
Hi @tcaputi 

> I'm not quite sure what you mean by "new" vs"existing" here. Could you elaborate more?

I mean the existing encryption root (here: pool2/encrypt) vs. a new created encryption root (here: pool2/newenc). The pool itself it not re-created. 

> Does this happen if you re-create everything from scratch? Are both systems using the same version of zfs?

I can´t re-create the entire pool. But as far as my tests have show (see above) sending a new created child from within the existing encryption root "pool2/encrypt" has the error, while a new created encryption root (pool2/newenc) does not.

And yes, both systems (see the version info at the top) have exactly the same version.

> having the zfs send file would probably be good too. Feel free to share it any way you see fit (so long as it does not have sensitive data).

I wil provide you with two dumps (they only contain the spl sources - so not perfonal data in it):

The first dump does not work and originates from a new created file system under an exisiting encryption root (pool2/encrypt):

```
# zfs get creation pool2/encrypt
NAME           PROPERTY  VALUE                  SOURCE
pool2/encrypt  creation  Sat Sep  2  5:56 2017  -
# zfs create pool2/encrypt/tmp
# cp -r /usr/src/spl /pool2/encrypt/tmp
# zfs snapshot pool2/encrypt/tmp@transfer_1

# zfs send -c -w pool2/encrypt/tmp@transfer_1 | ssh TARGET zfs recv backup/test
cannot receive new filesystem stream: invalid backup stream
# zfs send -c -w pool2/encrypt/tmp@transfer_1 > encrypt-does-not-work.zfs
```
**Note that adding "-s" for receive will render the pool unusable. So use with caution!**

The second dump does work and originates from a **new** created encryption root and new file system under it (pool2/newenc):

# echo "password" | zfs create -o encryption=aes-256-gcm -o keyformat=passphrase pool2/newenc
# zfs create pool2/newenc/temp
# cp -r /usr/src/spl /pool2/newenc/temp/
# zfs snapshot pool2/newenc/temp@transfer_1
# zfs send -c -w pool2/newenc/temp@transfer_1 | ssh TARGET zfs recv backup/test

The dump files for download (150 MB) are [here](https://ronnyegner.de/nextcloud/dump.tar.bz2).

**Comment by tcaputi** [comment]
So there seem to be 2 problems here. The major issue is that your send file has invalid encryption parameters. Namely this (from `zstreamdump`):

```
                keyformat = 0x0
                pbkdf2iters = 0x0
                pbkdf2salt = 0x0
```

So you have no keyformat, pbkdf2iters or pbkdf2salt. On the recv side, this is correctly detected as an invalid send stream which is producing the error you see. However, the second (smaller) problem is that the receive side isn't cleaning up after itself well when the send fails. That should be easy enough to fix.

Can you send me the output of `zdb -dddd pool2`? Also, did you create the original encrypted dataset on the commit you listed above or on the pull request before it was merged into master? Have you performed any commands to alter encryption properties (such as `zfs change-key`)?

Thanks for any info.

**Comment by ronnyegner** [comment]
Hi,

> Can you send me the output of zdb -dddd pool2? 
WIll provide asap. Probably tomorrow.

> Also, did you create the original encrypted dataset on the commit you listed above or on the pull request before it was merged into master? 

I am running the version listed above since 31 Aug. This version includes (as far as i can see) the commit #6545 . The original encrypted data set was created on 2nd Sep - so a few days afterwards and with the PR merged into master.
Here you can see the install date of the modules in /lib/modules/´uname -r` directory:

`-rw-r--r--  1 root root 3230296 Aug 31 13:12 zfs.ko
`


> Have you performed any commands to alter encryption properties (such as zfs change-key)?

No. I created the encrypted dataset and that´s it. Never changed the key or altered any encryption properties.

**Comment by tcaputi** [comment]
Nevermind. I don't need anymore information. I am able to reproduce the issue with the following script:

```
zpool create -f pool sdb
zpool create -f backup sdc
echo password | zfs create -o encryption=on -o keyformat=passphrase pool/encrypt
zfs umount pool/encrypt
zfs unload-key pool/encrypt # required to cause the bug
echo password | zfs mount -l pool/encrypt
zfs create pool/encrypt/tmp
cp -r /etc /pool/encrypt/tmp
zfs snapshot pool/encrypt/tmp@transfer_1
zfs send -c -w pool/encrypt/tmp@transfer_1 | zfs recv -s backup/test
```

I should be able to fix this shortly now.

**Comment by tcaputi** [comment]
I have a fix for this locally now and will push it a bit later today after some testing.

**Comment by UralZima** [comment]
Hello. I am experiencing similar issue https://github.com/zfsonlinux/zfs/issues/6732  and have some detailed information. But my case is I can't send newly created encrypted datasets (with latest zfs version) on old upgraded pool. Please help

**Comment by tcaputi** [comment]
@UralZima Have you tried using #6595? This issue should be fixed there.

**Comment by UralZima** [comment]
No, still not. I need to figure out how to add this PR to zfs in my portage in gentoo. 

When you are ready to commit this to master? Also reboots are very painful for me, after encryption was merged I have updated the kernel and zfs on my remote high-load server (very painful), and want to send datastreams there. Want to be sure it will work well and I will not need to update kernel and reboot often. 
I want to update my server again after your commit to master.

Huh, well that I don't tried to send streams to my server, because I corrupted my local pools with -s option.

**Comment by tcaputi** [comment]
If you are looking for stability, I would recommend waiting for the next major release of zfs before using encryption. Encryption was merged only a month ago and was a very large patch. #6595 fixes all of the known issues with the patch so far, but I'm sure there will be more in the following weeks and months. In general, if reboots are painful for you and you don't have an easy way to recover from bugs and data loss I would not recommend using bleeding edge code from any project, not just zfs.

I'm not sure when the patch will be merged. I am hoping for early next week, but the patch still needs review and if someone finds new problems with encryption that might delay the patch further.

**Comment by UralZima** [comment]
Basicly I need to use my remote server for sending raw streams as backups, I was using stable zfs before, but this feature is very needed.

I'll try this PR on my local machine and will report here if something fails. Hope will be merged soon. Thanks

**Comment by ronnyegner** [comment]
@UralZima @tcaputi  I would like to test this as well... but i have no clue how since the code is not yet in the master code. Can you give me some hints please?

**Comment by tcaputi** [comment]
@ronnyegner It should be in master very soon at this point. At this point it might be easier to simply wait.

**Comment by ronnyegner** [comment]
OK. Thanks. I will be patient.

**Comment by ronnyegner** [comment]
Solved with #6595

**Comment by mailinglists35** [comment]
I am getting the same error, on 0.8.3, when sending unencrypted to encrypted.

````
root@prod-pool:~# zfs send -L -c -e  'prod-pool/backups'@'zfs-auto-snap_hourly-2017-06-22-1549' | zfs receive  -s -F 'bkp-wd-3tb/prod-pool/backups'
cannot receive new filesystem stream: kernel modules must be upgraded to receive this stream.
root@prod-pool:~# zpool get all prod-pool; zfs get all 'prod-pool/backups'@'zfs-auto-snap_hourly-2017-06-22-1549'; zpool get all bkp-wd-3tb; zfs get all bkp-wd-3tb/prod-pool
NAME     PROPERTY                       VALUE                          SOURCE
prod-pool  size                           1008G                          -
prod-pool  capacity                       74%                            -
prod-pool  altroot                        -                              default
prod-pool  health                         ONLINE                         -
prod-pool  guid                           7367461532570993000            -
prod-pool  version                        -                              default
prod-pool  bootfs                         -                              default
prod-pool  delegation                     on                             default
prod-pool  autoreplace                    off                            default
prod-pool  cachefile                      -                              default
prod-pool  failmode                       continue                       local
prod-pool  listsnapshots                  off                            default
prod-pool  autoexpand                     off                            default
prod-pool  dedupditto                     0                              default
prod-pool  dedupratio                     1.76x                          -
prod-pool  free                           259G                           -
prod-pool  allocated                      749G                           -
prod-pool  readonly                       off                            -
prod-pool  ashift                         0                              default
prod-pool  comment                        compatibil cu release 0.7      local
prod-pool  expandsize                     -                              -
prod-pool  freeing                        0                              -
prod-pool  fragmentation                  24%                            -
prod-pool  leaked                         0                              -
prod-pool  multihost                      off                            default
prod-pool  checkpoint                     -                              -
prod-pool  load_guid                      11069892969105022052           -
prod-pool  autotrim                       off                            default
prod-pool  feature@async_destroy          enabled                        local
prod-pool  feature@empty_bpobj            active                         local
prod-pool  feature@lz4_compress           active                         local
prod-pool  feature@multi_vdev_crash_dump  disabled                       local
prod-pool  feature@spacemap_histogram     active                         local
prod-pool  feature@enabled_txg            active                         local
prod-pool  feature@hole_birth             active                         local
prod-pool  feature@extensible_dataset     active                         local
prod-pool  feature@embedded_data          active                         local
prod-pool  feature@bookmarks              active                         local
prod-pool  feature@filesystem_limits      enabled                        local
prod-pool  feature@large_blocks           enabled                        local
prod-pool  feature@large_dnode            active                         local
prod-pool  feature@sha512                 disabled                       local
prod-pool  feature@skein                  disabled                       local
prod-pool  feature@edonr                  disabled                       local
prod-pool  feature@userobj_accounting     disabled                       local
prod-pool  feature@encryption             disabled                       local
prod-pool  feature@project_quota          disabled                       local
prod-pool  feature@device_removal         disabled                       local
prod-pool  feature@obsolete_counts        disabled                       local
prod-pool  feature@zpool_checkpoint       disabled                       local
prod-pool  feature@spacemap_v2            disabled                       local
prod-pool  feature@allocation_classes     disabled                       local
prod-pool  feature@resilver_defer         disabled                       local
prod-pool  feature@bookmark_v2            disabled                       local
NAME                                                  PROPERTY                    VALUE                       SOURCE
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  type                        snapshot                    -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  creation                    Thu Jun 22 18:49 2017       -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  used                        11K                         -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  referenced                  21K                         -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  compressratio               1.00x                       -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  devices                     on                          default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  exec                        on                          default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  setuid                      on                          default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  createtxg                   492820226                   -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  xattr                       on                          default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  version                     5                           -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  utf8only                    off                         -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  normalization               none                        -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  casesensitivity             sensitive                   -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  nbmand                      off                         default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  guid                        7400248227257122248         -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  primarycache                all                         default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  secondarycache              all                         default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  defer_destroy               off                         -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  userrefs                    0                           -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  objsetid                    4560                        -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  mlslabel                    none                        default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  refcompressratio            1.00x                       -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  written                     21K                         -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  clones                                                  -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  logicalreferenced           10.5K                       -
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  acltype                     off                         default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  context                     none                        default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  fscontext                   none                        default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  defcontext                  none                        default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  rootcontext                 none                        default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  encryption                  off                         default
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  com.sun:auto-snapshot-desc  -                           local
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  autobackup:enabled          true                        inherited from prod-pool/backups
prod-pool/backups@zfs-auto-snap_hourly-2017-06-22-1549  com.sun:auto-snapshot       true                        inherited from prod-pool
NAME        PROPERTY                       VALUE                          SOURCE
bkp-wd-3tb  size                           2.72T                          -
bkp-wd-3tb  capacity                       0%                             -
bkp-wd-3tb  altroot                        -                              default
bkp-wd-3tb  health                         ONLINE                         -
bkp-wd-3tb  guid                           18238865307624152800           -
bkp-wd-3tb  version                        -                              default
bkp-wd-3tb  bootfs                         -                              default
bkp-wd-3tb  delegation                     on                             default
bkp-wd-3tb  autoreplace                    off                            default
bkp-wd-3tb  cachefile                      -                              default
bkp-wd-3tb  failmode                       wait                           default
bkp-wd-3tb  listsnapshots                  off                            default
bkp-wd-3tb  autoexpand                     off                            default
bkp-wd-3tb  dedupditto                     0                              default
bkp-wd-3tb  dedupratio                     1.00x                          -
bkp-wd-3tb  free                           2.72T                          -
bkp-wd-3tb  allocated                      3.01M                          -
bkp-wd-3tb  readonly                       off                            -
bkp-wd-3tb  ashift                         0                              default
bkp-wd-3tb  comment                        -                              default
bkp-wd-3tb  expandsize                     -                              -
bkp-wd-3tb  freeing                        0                              -
bkp-wd-3tb  fragmentation                  0%                             -
bkp-wd-3tb  leaked                         0                              -
bkp-wd-3tb  multihost                      off                            default
bkp-wd-3tb  checkpoint                     -                              -
bkp-wd-3tb  load_guid                      8154567835616945215            -
bkp-wd-3tb  autotrim                       off                            default
bkp-wd-3tb  feature@async_destroy          enabled                        local
bkp-wd-3tb  feature@empty_bpobj            active                         local
bkp-wd-3tb  feature@lz4_compress           active                         local
bkp-wd-3tb  feature@multi_vdev_crash_dump  enabled                        local
bkp-wd-3tb  feature@spacemap_histogram     active                         local
bkp-wd-3tb  feature@enabled_txg            active                         local
bkp-wd-3tb  feature@hole_birth             active                         local
bkp-wd-3tb  feature@extensible_dataset     active                         local
bkp-wd-3tb  feature@embedded_data          active                         local
bkp-wd-3tb  feature@bookmarks              enabled                        local
bkp-wd-3tb  feature@filesystem_limits      enabled                        local
bkp-wd-3tb  feature@large_blocks           enabled                        local
bkp-wd-3tb  feature@large_dnode            active                         local
bkp-wd-3tb  feature@sha512                 enabled                        local
bkp-wd-3tb  feature@skein                  enabled                        local
bkp-wd-3tb  feature@edonr                  enabled                        local
bkp-wd-3tb  feature@userobj_accounting     active                         local
bkp-wd-3tb  feature@encryption             active                         local
bkp-wd-3tb  feature@project_quota          active                         local
bkp-wd-3tb  feature@device_removal         enabled                        local
bkp-wd-3tb  feature@obsolete_counts        enabled                        local
bkp-wd-3tb  feature@zpool_checkpoint       enabled                        local
bkp-wd-3tb  feature@spacemap_v2            active                         local
bkp-wd-3tb  feature@allocation_classes     enabled                        local
bkp-wd-3tb  feature@resilver_defer         enabled                        local
bkp-wd-3tb  feature@bookmark_v2            enabled                        local
NAME                PROPERTY              VALUE                     SOURCE
bkp-wd-3tb/prod-pool  type                  filesystem                -
bkp-wd-3tb/prod-pool  creation              Wed Feb 12 16:07 2020     -
bkp-wd-3tb/prod-pool  used                  296K                      -
bkp-wd-3tb/prod-pool  available             2.63T                     -
bkp-wd-3tb/prod-pool  referenced            296K                      -
bkp-wd-3tb/prod-pool  compressratio         1.00x                     -
bkp-wd-3tb/prod-pool  mounted               no                        -
bkp-wd-3tb/prod-pool  quota                 none                      default
bkp-wd-3tb/prod-pool  reservation           none                      default
bkp-wd-3tb/prod-pool  recordsize            128K                      default
bkp-wd-3tb/prod-pool  mountpoint            /srv/bkp-prod-pool/prod-pool  inherited from bkp-wd-3tb
bkp-wd-3tb/prod-pool  sharenfs              off                       default
bkp-wd-3tb/prod-pool  checksum              on                        default
bkp-wd-3tb/prod-pool  compression           on                        inherited from bkp-wd-3tb
bkp-wd-3tb/prod-pool  atime                 off                       inherited from bkp-wd-3tb
bkp-wd-3tb/prod-pool  devices               on                        default
bkp-wd-3tb/prod-pool  exec                  on                        default
bkp-wd-3tb/prod-pool  setuid                on                        default
bkp-wd-3tb/prod-pool  readonly              off                       default
bkp-wd-3tb/prod-pool  zoned                 off                       default
bkp-wd-3tb/prod-pool  snapdir               hidden                    default
bkp-wd-3tb/prod-pool  aclinherit            restricted                default
bkp-wd-3tb/prod-pool  createtxg             19                        -
bkp-wd-3tb/prod-pool  canmount              on                        default
bkp-wd-3tb/prod-pool  xattr                 sa                        inherited from bkp-wd-3tb
bkp-wd-3tb/prod-pool  copies                1                         default
bkp-wd-3tb/prod-pool  version               5                         -
bkp-wd-3tb/prod-pool  utf8only              off                       -
bkp-wd-3tb/prod-pool  normalization         none                      -
bkp-wd-3tb/prod-pool  casesensitivity       sensitive                 -
bkp-wd-3tb/prod-pool  vscan                 off                       default
bkp-wd-3tb/prod-pool  nbmand                off                       default
bkp-wd-3tb/prod-pool  sharesmb              off                       default
bkp-wd-3tb/prod-pool  refquota              none                      default
bkp-wd-3tb/prod-pool  refreservation        none                      default
bkp-wd-3tb/prod-pool  guid                  3607903992732689065       -
bkp-wd-3tb/prod-pool  primarycache          all                       default
bkp-wd-3tb/prod-pool  secondarycache        all                       default
bkp-wd-3tb/prod-pool  usedbysnapshots       0B                        -
bkp-wd-3tb/prod-pool  usedbydataset         296K                      -
bkp-wd-3tb/prod-pool  usedbychildren        0B                        -
bkp-wd-3tb/prod-pool  usedbyrefreservation  0B                        -
bkp-wd-3tb/prod-pool  logbias               latency                   default
bkp-wd-3tb/prod-pool  objsetid              134                       -
bkp-wd-3tb/prod-pool  dedup                 off                       default
bkp-wd-3tb/prod-pool  mlslabel              none                      default
bkp-wd-3tb/prod-pool  sync                  standard                  default
bkp-wd-3tb/prod-pool  dnodesize             auto                      inherited from bkp-wd-3tb
bkp-wd-3tb/prod-pool  refcompressratio      1.00x                     -
bkp-wd-3tb/prod-pool  written               296K                      -
bkp-wd-3tb/prod-pool  logicalused           104K                      -
bkp-wd-3tb/prod-pool  logicalreferenced     104K                      -
bkp-wd-3tb/prod-pool  volmode               default                   default
bkp-wd-3tb/prod-pool  filesystem_limit      none                      default
bkp-wd-3tb/prod-pool  snapshot_limit        none                      default
bkp-wd-3tb/prod-pool  filesystem_count      none                      default
bkp-wd-3tb/prod-pool  snapshot_count        none                      default
bkp-wd-3tb/prod-pool  snapdev               hidden                    default
bkp-wd-3tb/prod-pool  acltype               off                       default
bkp-wd-3tb/prod-pool  context               none                      default
bkp-wd-3tb/prod-pool  fscontext             none                      default
bkp-wd-3tb/prod-pool  defcontext            none                      default
bkp-wd-3tb/prod-pool  rootcontext           none                      default
bkp-wd-3tb/prod-pool  relatime              off                       default
bkp-wd-3tb/prod-pool  redundant_metadata    all                       default
bkp-wd-3tb/prod-pool  overlay               off                       default
bkp-wd-3tb/prod-pool  encryption            aes-256-gcm               -
bkp-wd-3tb/prod-pool  keylocation           prompt                    local
bkp-wd-3tb/prod-pool  keyformat             passphrase                -
bkp-wd-3tb/prod-pool  pbkdf2iters           342K                      -
bkp-wd-3tb/prod-pool  encryptionroot        bkp-wd-3tb/prod-pool        -
bkp-wd-3tb/prod-pool  keystatus             available                 -
bkp-wd-3tb/prod-pool  special_small_blocks  0                         default
root@prod-pool:~# zfs --version
zfs-0.8.3-1~rlaager1.18.04.1
zfs-kmod-0.8.3-1~rlaager1.18.04.1
root@prod-pool:~# uname -r
4.15.0-76-generic
````

**Comment by mailinglists35** [comment]
oh, nevermind.

-e --embed [...] Datasets that are sent with this flag may not be received as an encrypted
           dataset, since encrypted datasets cannot use the embedded_data feature. 

this should be in the faq...
