### ISSUE TITLE
mounting encrypted dataset fails with "Invalid exchange"

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#7217]
this pool was Feb 18th and a new SSD arrived so I intended on doing testing and tried to zpool split the mirror to create two separate pools, but that didn't work (reported an issue for it)

I tried to send/recv the entire rpool to rpool2 and this seemed to work until I exported and imported - I could no longer mount the filesystems.

some issue is preventing mount of encrypted datasets - it kind-of looks like it's only when they are created by receiving a raw+replicated send stream..

unfortunately, I tried to reproduce the issue on the previously working commit, and it seems to happen there, too, but it's not clear if I was actually able to compile the previous version or not.

`send -w` by itself seemed to work;

```                                     
[:)] # zpool create -f -o ashift=13 rpool2 /dev/sdb4           
[:)] # zfs send -w rpool/ocean/GENTOO/ROOT@1519103701 | mbuffer -m 2G | zfs recv -Fs rpool2/ROOT 
in @  0.0 KiB/s, out @ 44.5 MiB/s, 19.4 GiB total, buffer   1% full
summary: 19.5 GiByte in  1min 15.5sec - average of  264 MiB/s
[:)] # zfs load-key rpool2/ROOT                                                                 
Enter passphrase for 'rpool2/ROOT': 
[:)] # zfs mount rpool2/ROOT                                                                    
[:)] # zpool export rpool2     
[:)] # zpool import -l rpool2 -R /altroot           
Enter passphrase for 'rpool2/ROOT': 
1 / 1 keys successfully loaded
[:)] # zfs mount rpool2/ROOT
cannot mount 'rpool2/ROOT': filesystem already mounted
[:(] # 
```

`send -Rw` does not
```
# zfs send -Rw rpool/ocean@1519103701 | mbuffer -m 2G | zfs recv -Fs rpool2/ocean
in @  0.0 KiB/s, out @ 1494 KiB/s, 76.6 GiB total, buffer   0% full
summary: 76.6 GiByte in  5min 58.0sec - average of  219 MiB/s
# zpool export rpool2                                                            
# zpool import -l rpool2 -R /altroot
Enter passphrase for 'rpool2/ocean': 
Enter passphrase for 'rpool2/ROOT': 
2 / 2 keys successfully loaded
cannot mount '/altroot': directory is not empty
filesystem 'rpool2/ocean/HOME/kash' can not be mounted: Invalid exchange
cannot mount 'rpool2/ocean/HOME/kash': Invalid argument
filesystem 'rpool2/ocean/GENTOO/USR/SRC' can not be mounted: Invalid exchange
cannot mount 'rpool2/ocean/GENTOO/USR/SRC': Invalid argument
```

I built a new initrd based on master and datasets did not mount on boot. I added #7210 in the hopes it would resolve the condition but it does not.

the funny thing is my current initrd and kernel module (that I can't find the commit of, but seems to be from Feb 19th) allows me to mount the dataset and I can boot.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | 
Distribution Version    | 
Linux Kernel                 | 
Architecture                 | 
ZFS Version                  | working: v0.7.0-316_ge921f650,, not working: 0.7.0-330_g09302a4c
SPL Version                  | working: v0.7.0-26_g48ef8ba, not working: 0.7.0-29_g378c6ed

**Comment by tcaputi** [comment]
Hmmm. interesting. Let me look into this today and tomorrow.

**Comment by tcaputi** [comment]
I noticed in your snippets that in your working example you only sent `ROOT`. That dataset didn't appear to have a problem in the `-wR` case either. did you try sending the ALL of the other datasets with with just `-w`?

**Comment by kpande** [comment]
I can't, `-R` requires `-w`. I tried sending each individually, no go.

**Comment by kpande** [comment]
(if we could get `-R` to work without `-w` that would be most excellent - it's not clear why it won't work, as-is)

**Comment by tcaputi** [comment]
> I can't, -R requires -w. I tried sending each individually, no go.

I meant sending them each individually. By nogo you mean they don't mount like that either? Basically what I'm asking is you can cause the issue without `zfs send -Rw`?

> (if we could get -R to work without -w that would be most excellent - it's not clear why it won't work, as-is)

Working on it. The reason is that the encryption code isnt yet integrated with `zfs recv -o / -x`, and there are a lot of complications and edge cases that come up related to encryptionroot hierarchy when you do a recursive raw send. This is the next thing on my list to work on, but for the moment I'm trying to work on stability (which as you can see is still a bit of an issue :))

**Comment by kpande** [comment]
that's funny because I was going to say, if only `-o` and `-x` worked (I already brought this up to you) then we'd be able to use `-R` no problem ;D

but they do mount when sending with -w only, but well, I wanted to send all the snapshots and properties (and keys)

**Comment by tcaputi** [comment]
So this * only * happens when you use `-R`. That's pretty interesting. That helps a lot. I'll look into it tomorrow.

**Comment by kpande** [comment]
@tcaputi the odd part is how my currently-running ZFS will mount my rpool but then the latest ZFS won't (once it's included in the initrd, I can't even boot)

**Comment by kpande** [comment]
@tcaputi I did receive the rpool initially  but you'd think if there were only an issue with recv then it wouldn't mount my rpool either.. but once it boots from rpool I can freely reproduce the Invalid exchange, so this older version isn't 100% either.

**Comment by tcaputi** [comment]
How long ago did you receive the rpool? There was a brief period where there was an incompatibility with encryption and the new project quota code. All of the known bugs related to this were fixed in 7b30ee6bafe91ebd3b34433ef3b943fd07a98cea, 163a8c28dd7084bd85a32968c2b7941e99ead161, and f8478fc2ca8d62f9562a4284426e8d3bd41c0cf0

**Comment by kpande** [comment]
seems that the `-d` argument to recv is what causes the `does not exist` error.

**Comment by kpande** [comment]
I did try reverting to ZFS version before those commits because I did remember seeing them, but it still does the same thing in the initrd..

**Comment by kpande** [comment]
so i managed to use ZFS 316 to send my datasets to an unencrypted pool and then boot into ZFS 330 successfully (without encryption, but also without `-R` or `-w` because both are incompatible with decrypting a send stream, since `-o encryption=off` can't be specified), then once again send/recv my data to the recreated `rpool` and encrypt it the same way it was before.

now I'm able to mount all of my encrypted datasets and booted into zfs 330 on an encrypted root, but I'm hitting the same error that popped up earlier when splitting zpool (@prometheanfire has mentioned it in his own ticket)

```
[ 1049.376479] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, dsobj, bp, zio->io_txg, psize, zio->io_abd, eabd, iv, mac, salt, &no_crypt)) failed (0 == 2)
[ 1049.376484] PANIC at zio.c:3866:zio_encrypt()
[ 1049.376486] Showing stack for process 13445
[ 1049.376489] CPU: 0 PID: 13445 Comm: z_wr_iss Tainted: P           O    4.14.20-gentoo #1
[ 1049.376490] Hardware name:                  /DX79TO, BIOS SIX7910J.86A.0650.2014.0307.0138 03/07/2014
[ 1049.376492] Call Trace:
[ 1049.376501]  dump_stack+0x63/0x81
[ 1049.376508]  spl_dumpstack+0x42/0x50 [spl]
[ 1049.376511]  spl_panic+0xc8/0x110 [spl]
[ 1049.376514]  ? spl_kmem_cache_alloc+0x64/0xa20 [spl]
[ 1049.376534]  ? spa_do_crypt_abd+0x44/0x4f0 [zfs]
[ 1049.376543]  zio_push_transform+0x5bb/0x12d0 [zfs]
[ 1049.376554]  ? zio_push_transform+0xc95/0x12d0 [zfs]
[ 1049.376564]  zio_execute+0x90/0x4d0 [zfs]
[ 1049.376566]  taskq_dispatch_delay+0x5b1/0x900 [spl]
[ 1049.376569]  ? wake_up_q+0x80/0x80
[ 1049.376579]  ? zio_interrupt+0x17c0/0x17c0 [zfs]
[ 1049.376582]  kthread+0x128/0x140
[ 1049.376584]  ? taskq_dispatch_delay+0x320/0x900 [spl]
[ 1049.376585]  ? kthread_create_on_node+0x40/0x40
[ 1049.376587]  ? kthread_create_on_node+0x40/0x40
[ 1049.376589]  ret_from_fork+0x35/0x40

```

**Comment by prometheanfire** [comment]
we should probably combine our backtraces into voltron

**Comment by tcaputi** [comment]
@kpande 
> now I'm able to mount all of my encrypted datasets and booted into zfs 330 on an encrypted root

This makes sense. Like I was trying to say above (but I'm not sure if it was clear), the new projectquota code which was merged about a week ago had some on-disk incompatibilities with the encryption code; The project quota data which was added wasn't being properly protected. If you created these datasets on thee code that did not have that problem fixed you would definitely see those problems. 

> but I'm hitting the same error that popped up earlier when splitting zpool (@prometheanfire has mentioned it in his own ticket)

Not sure what you mean by ZFS 316 and ZFS 330. Can you try with the current code on master (if you haven't already) and see if it fixes the `spa_do_crypt_abd()` problem for you?

**Comment by kpande** [comment]
316 and 330 refer to build numbers, as referenced initially in the OP

`working: v0.7.0-316_ge921f650,, not working: 0.7.0-330_g09302a4c`

**Comment by tcaputi** [comment]
> 316 and 330 refer to build numbers, as referenced initially in the OP

I see. That has all the fixes so this must be something new. Let's consolidate this in #7215 since that appears to be the same issue at this point

**Comment by kpande** [comment]
we should leave this one open so that the errata for the pool can be tracked instead of the nasty "won't mount at boot" issue

**Comment by tcaputi** [comment]
> we should leave this one open so that the errata for the pool can be tracked instead of the nasty "won't mount at boot" issue

I'm not completely sure how we want to handle this. The problem only existed for about 4 days so I'm not sure if we want to make a full errata listing for it and I'm not sure what the criteria should be for closing this. @behlendorf any thoughts here?

**Comment by kpande** [comment]
a few people were testing encryption in this time window since the fix had been merged so there's bound to be more than 1 more person asking, it's up to you and @behlendorf though

**Comment by prometheanfire** [comment]
Let me see if I got this right.

~4 days ago a bug was introduced that caused pools/datasets created with that version to be on disk incompat.
~12 hours ago it was fixed

that it? (want to know if I need to recreate my pool).

**Comment by kpande** [comment]
if you upgraded the pool (I didn't realize I had?) to enable that feature then it is affected, apparently. but if master will load everything, no problem.

**Comment by prometheanfire** [comment]
ah, ya, doesn't look like I have that enabled yet

**Comment by prometheanfire** [comment]
I might have booted a kernel without the fix, but not with project_quotas enabled

**Comment by kdwinter** [comment]
I'm afraid I've been hit by this issue as well. Yesterday I upgraded my pool, which contains only encrypted datasets, as advised by zpool status. Today after a fresh boot I can no longer import, mount, or run any zfs-related commands without them timing out or completely locking up the system. `dmesg` is also full of "Tainted" call traces.

I have since updated to the latest master code, but that did not fix the above issues, and I'm still receiving panics and tainted traces. What's the recommended way of fixing my pool?

**Comment by tcaputi** [comment]
@kdwinter It looks like you started using the code from master at the wrong time. Good news is that I think your data is fine (as far as I can tell). Your zfs commands are hanging because of a failed ASSERT in the code. I will be working to resolve that first thing tomorrow, but until I can figure out what's wrong and come up with a fix you might have to just hang tight.

Side note: "tainted" doesn't mean anything important, it's just Linux complaining that zfs isn't GPL licensed.

**Comment by kdwinter** [comment]
Thanks for the followup. Hopefully the data is indeed fine, as I have to admit I did not consider *this* kind of issue to be a possible cause for data loss. Lesson learned, preferably not the hard way! :)

**Comment by kdwinter** [comment]
@tcaputi Any update on this?

**Comment by tcaputi** [comment]
We are tracking that issue here: https://github.com/zfsonlinux/zfs/issues/7215. I posted an update last night. I hope to have it fixed by tomorrow morning.

**Comment by tcaputi** [comment]
@kpande Are we good to close this issue?

**Comment by kpande** [comment]
this isn't resolved per se but in either case users will need to send/recv, they can't mount on new version but the chance of hitting the issue is low.

**Comment by jefferai** [comment]
@tcaputi Sorry to bug on a closed issue, but it's not clear to me the right way to solve this problem if you're affected. I do have `-2` as an object in `zdb -dd` for my encrypted data sets and I do get the error `filesystem <fs> can not be mounted: Invalid exchange` but I'm not hitting any panics and I'm not trying to split a pool as in #7215.

I went from e921f6508 where things were working (after I took care of the errata on the pool by rebuilding my data sets via send/receive) to 639b18944.

My root data set in the pool isn't encrypted; I took care due to the previous round of sending/receiving to instead encrypt a couple of top level data sets instead. It sounds like maybe? I just need to create a new top level encrypted data set and do a recursive send/receive? Which should work even though the sets can't be mounted? I'd really appreciate some guidance here.

**Comment by kpande** [comment]
mount using an old version.

if you're wanting to keep it encrypted, send it to a new pool in a VM or on a separate system, running the latest git tip.

if you want to keep it unencrypted, you can send it unencrypted to the local pool and then destroy the encrypted copy before upgrading.

if you don't mind temporary exposure you can decrypt and then reencrypt once you reboot into the newer version.

**Comment by tcaputi** [comment]
@jefferai What @kpande said is basically correct. I'm sorry this isn't more convenient but it seems like you are one of a few people who started using encryption at a bad time. If you encounter this kind of problem again with any datasets created from the current git master code going forward, please make a new issue and I will look into it as soon as possible.

**Comment by kpande** [comment]
@tcaputi it seems like more people ran into this than we thought originally and might make sense to introduce Eratta 4.

**Comment by tcaputi** [comment]
I will talk to Brian about it tomorrow (we're having a snowpocalypse over here on the East coast US).

**Comment by tcaputi** [comment]
> Basically I just want to understand whether there is something specific about needing to send it to a different pool as opposed to a different data set that is encrypted and created with latest git.

No you don't need to send it to a different pool. The only thing that needs to happen is that the data needs to be re-encrypted with the latest code (so don't use `zfs send -w`). It may be possible that your encrypted datasets won't mount or send now with the latest code so what you will have to do is revert to the old code, send the data in plaintext (you can just keep the send files or you can receive them as unencrypted datasets), upgrade to the newest version, and receive all of your plaintext send files as encrypted datastes by receiving them under an encryption root.

**Comment by jefferai** [comment]
Thank you! I've rolled back and it's successfully sending -- failed with latest git code, so to an unencrypted data set at the moment, then will transfer back after re-upgrading.

Native encryption in ZoL is fantastic, and I'm happy taking the good with the bad as part of being an early adopter. Keep on keeping on!
